### ISSUE TITLE
404 for APT3_Round1_Navigator_layer.json on AttackEvals Round 1 Writeup

### ISSUE THREAD

**Issue by Bojak4616** [mitre-attack/attack-navigator#100]
Currently, a dead link exists on https://attackevals.mitre.org/methodology/round1/scope that should show an ATT&CK heatmap for APT3 used for Round1 evals. I don't know if this is an issue that should be resolved at the https://attackevals.mire.org level or if `APT3_Round1_Navigator_layer.json` has been moved/deleted from this repository. 

The dead link is listed below: 

https://mitre-attack.github.io/attack-navigator/enterprise/#layerURL=https://raw.githubusercontent.com/mitre-attack/attack-evals/master/APT3_Round1_Navigator_layer.json

**Comment by isaisabel** [comment]
Hi @Bojak4616,

This is an issue with the ATT&CK evals site itself, not the navigator. However, I'll let them know that their link is broken.
