### ISSUE TITLE
require 'fs' no longer supported - compilation failed 

### ISSUE THREAD

**Issue by michalgarcarz** [mitre-attack/attack-navigator#104]
Hello Team,

npm --version: 6.10.3
nodejs --version: v12.10.0
Angular CLI: 8.0.1
Ubuntu 18.04.3 LTS

When compiling i got:

`root@ss:~/ss/attack-navigator/nav-app# ng serve --host 0.0.0.0 --disableHostCheck
Your global Angular CLI version (8.3.6) is greater than your local
version (8.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
WARNING: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.

Date: 2019-09-30T12:02:24.872Z
Hash: f52a2942dd1e3104a3fb
Time: 19412ms
chunk {main} main.js, main.js.map (main) 629 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 562 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 462 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 2.18 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 197 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.59 MB [initial] [rendered]

ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/exceljs/dist/es5/csv'
ERROR in ./node_modules/exceljs/dist/es5/utils/utils.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/exceljs/dist/es5/utils'
ERROR in ./node_modules/exceljs/dist/es5/xlsx/xlsx.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/exceljs/dist/es5/xlsx'
ERROR in ./node_modules/fast-csv/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'fs' in '/root/ss/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.`

Do i understand correctly that "require fs" is no longer supported in newer Angular ? Could you please provide the recommendation ?

Thanks,
Michal

**Comment by isaisabel** [comment]
Hi @michalgarcarz,

 It looks like the `postinstall` step was not run. This step was implemented to fix the `fs` issue, and is _supposed_ to run automatically after `npm install`. However, previous bug reports imply that it doesn't run automatically in certain environments. 

One of the following commands should fix your error:

1. `npm run postinstall`
2. `node patch-webpack.js`, which is the command postinstall would run anyway

Let me know if that works.

**Comment by michalgarcarz** [comment]
Hi @isaisabel - i have manually commented out all of 'fs require' but had some other challanges with webpack, your solution fix all of my issues - thanks !
