### ISSUE TITLE
export to json does not including tactics/techniques ?

### ISSUE THREAD

**Issue by michalgarcarz** [mitre-attack/attack-navigator#105]
Hello Team,

Not sure if that is a feature or bug: when exporting to json i do never have any selected technique nor tactic included. When importing back json i have empty layer (with all techniques/tactics). The content of most json files is like this:

`{
	"name": "layer",
	"version": "2.1",
	"domain": "mitre-enterprise",
	"description": "",
	"filters": {
		"stages": [
			"act"
		],
		"platforms": [
			"windows",
			"linux",
			"mac"
		]
	},
	"sorting": 0,
	"viewMode": 0,
	"hideDisabled": false,
	"techniques": [],
	"gradient": {
		"colors": [
			"#ff6666",
			"#ffe766",
			"#8ec843"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": true
}`

Could you please confirm ? This is a feature ? no techniques/tactics inside ?

Thanks,

**Comment by isaisabel** [comment]
Hi @michalgarcarz,

The user's current selection is not included in the downloaded layers. Selection (via clicking techniques with the mouse, for example) is intended to enable adding annotations to the selected techniques. Selection itself is not intended to be considered as an annotation.

Try adding a score, comment, or background color to the selected techniques. See the in-app help page (click the `?` in the top right corner) for details on how to do this. 

Only when annotations have been added will a technique be included in the downloaded Layer.

**Comment by michalgarcarz** [comment]
OK, thanks for the confirmation @isaisabel
