### ISSUE TITLE
techniques are bound to specific tactic and external configurations are ignored. 

### ISSUE THREAD

**Issue by alowenstein** [mitre-attack/attack-navigator#118]
Hi,

If I'm trying to load a new layer with, for example - Tactic: initial-access and Technique: T1223 with color and comment, nothing is updated. 
this prevents users from adding TTs from external vendors such as SafeBreach which might create new techniques but these cannot be applied to Tactics if they are not aligned with the current configuration.

Any chance to change this behavior?
Thank you.

**Comment by isaisabel** [comment]
Hi @alowenstein,

Layer files are interpreted as the set of annotations to be applied to the ATT&CK Matrix. Layers are not intended to allow the user to modify the layout or content of the matrix itself.

To modify the matrix layout, you can create your own instance of the Navigator with custom STIX data. See [here](https://github.com/mitre-attack/attack-navigator#loading-content-from-local-files) for instructions on how to load data from local files. 

To change the set or order of tactics in the matrix, you would modify the STIX objects of type `x_mitre_matrix` ([example](https://github.com/mitre/cti/blob/master/enterprise-attack/x-mitre-matrix/x-mitre-matrix--eafc1b4c-5e56-4965-bd4e-66a6a89c88cc.json#L24-L36)). To add a technique to a tactic, you would specify the tactic name under the `kill_chain_phases` of the technique ([example](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--03d7999c-1f4c-42cc-8373-e7690d318104.json#L32-L37)).

Please see the usage instructions on our MITRE/CTI repo [here](https://github.com/mitre/cti/blob/master/USAGE.md) for more information about encoding ATT&CK content in STIX2.0 format.

Please let me know if you have any additional questions.

**Comment by alowenstein** [comment]
Thank you @isaisabel for clarifying this. we can close this issue.
