### ISSUE TITLE
Add mitigations to multi-select

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#119]
As a user of the ATT&CK Navigator, I want to be able to select techniques according to their associated mitigations (course-of-actions).

**Comment by Richard1611** [comment]
Hi! 
What about this enhancement proposal? It was archived or did you achieve the integration?

**Comment by isaisabel** [comment]
Hi @Richard1611,

This feature was added as you can now access mitigations in the multiselect interface (previously it was only groups and software):
![image](https://user-images.githubusercontent.com/28868888/121885106-c0d7ad00-cce1-11eb-8a78-8e258d3c7d0f.png)
