### ISSUE TITLE
Update Navigator with new ICS and Cloud matricies

### ISSUE THREAD

**Issue by dmiklaus** [mitre-attack/attack-navigator#126]
We utilize the Navigator for security control gap analysis.  I work for a public utility and we are extremely interested in getting our ICS mappings displayed, but it looks like the navigator has not yet been updated with the new ICS matrix release (https://collaborate.mitre.org/attackics/index.php/Main_Page).

We are also invested heavily into cloud spaces and would love to see the Navigator expanded to cover the Cloud matrices as well (https://attack.mitre.org/matrices/enterprise/cloud/).

**Comment by TJLeach** [comment]
I'm working on ATT&CK to Security Controls, let's talk.

**Comment by isaisabel** [comment]
Hi @dmiklaus,

The ATT&CK Navigator already supports cloud platforms. Under the enterprise domain, click the filters button to show controls for filtering by platform. The cloud platforms are hidden by default.


![image](https://user-images.githubusercontent.com/28868888/72439682-5e3d5300-3775-11ea-9905-988ce686c758.png)

With regards to ATT&CK for ICS, the ICS domain is not currently integrated into the greater ATT&CK infrastructure (thus its inclusion on a separate wiki). As it matures we may eventually move it over to the primary infrastructure, which would include the ATT&CK Navigator. We don't have any information on the timeframe of this integration at this moment, but I'll leave this issue open to document the request.

Thank you!

**Comment by isaisabel** [comment]
You might also want to check out our ATT&CK for ICS blog post, which talks more about our approach and roadmap for the domain.

https://medium.com/mitre-attack/launching-attack-for-ics-2be4d2fb9b8

**Comment by dmiklaus** [comment]
Awesome, thank you very much @isaisabel , much appreciated, you all do great work!

**Comment by dmiklaus** [comment]
> I'm working on ATT&CK to Security Controls, let's talk.

This can be quite a talk, and would be easier through some sort of voice-call.

For quick mention, I use the Navigator for layer display and created/use the following layers:
- mapping of techniques to our SIEM rules
- mapping of controls/security technology to technique data sources
- layer of the above two combined to show complete coverage

This just gets you close to "are we covered for this technique, yes/no", but if you wanted to get into scoring how good the actual coverage per technique is, is a whole next level of effort, but definitely doable.

I would be happy to talk about this process with you further if you would like, but as I mentioned before, this would be much easier to facilitate through a voice-call.

**Comment by isaisabel** [comment]
Hi @dmiklaus,

I realize it's been quite a while since you opened this issue, but I just wanted to say that ICS is now supported in the Navigator as of version 4.0. I'm therefore closing this issue.
