### ISSUE TITLE
technique comparison tool for AT29 shows different/wrong results

### ISSUE THREAD

**Issue by emeierg** [mitre-attack/attack-navigator#151]
Compare test like this:
![image](https://user-images.githubusercontent.com/44072982/79918212-ce94e980-83e0-11ea-8561-f2c29190657f.png)

with results reported here:
https://attackevals.mitre.org/APT29/results/bitdefender/
https://attackevals.mitre.org/APT29/results/vmware/

Also when you mouse-over the pop-up icon for show configuration it shows a different vendor.
![image](https://user-images.githubusercontent.com/44072982/79918369-1e73b080-83e1-11ea-800a-138c5884408b.png)

Data is all over the place and nothing shown in that tool is reliable. Please fix that.

When it works this is a helpful tool although the reports with options to filter are great too.

Thank you.

**Comment by emeierg** [comment]
It looks like, when you do a page refresh in the browser then it shows the wrong results, it fixes itself.

That is on Windows 10, Chrome 81.0.4044.113

**Comment by isaisabel** [comment]
Hi @emeierg,

We believe the bug has been patched but if you're still seeing it let us know. Regardless, this really isn't an ATT&CK Navigator issue, but rather an ATT&CK Evals issue. We'd recommend submitting bug reports relating to the Evals site to their issue tracker [here](https://github.com/mitre-attack/attack-evals/issues)
