### ISSUE TITLE
First mention of MITRE ATT&CK® does not comply with https://attack.mitre.org/resources/faq/

### ISSUE THREAD

**Issue by joachimmetz** [mitre-attack/attack-navigator#165]
The first mention of MITRE ATT&CK® on https://github.com/mitre-attack/attack-navigator
```
Web app that provides basic navigation and annotation of ATT&CK matrices 
```

Does not comply with https://attack.mitre.org/resources/faq/
```
Your first references in writing must include "MITRE" preceding "ATT&CK®" - but subsequently should just reference "ATT&CK" (no registered trademark symbol required).
```

Please update this page or change your policy around the use of the name

**Comment by joachimmetz** [comment]
You could also consider `mitre-attack/attack-navigator` in the github organization name to be the first mention. However then it violates:
```
Do not modify the trademark, such as through hyphenation or abbreviation. For example, "ATT&CK'd!", "Plan-of-ATT&CK", "ATTK".
```

**Comment by joachimmetz** [comment]
@isaisabel could you add some explanation so other understand what is or is not necessary here?

**Comment by isaisabel** [comment]
The guidance on our FAQ is intended for organizations or individuals intending to cite or use ATT&CK. The components of the ATT&CK Infrastructure (e.g the Navigator, Website) do not need to rigidly adhere to that guidance because they are created and maintained by ATT&CK itself.

**Comment by joachimmetz** [comment]
@isaisabel thx for that context. However could you add some advisory on this project then for those that want to refer to this project or the framework on how they should be properly doing this in compliance with these rules imposed on others?
