### ISSUE TITLE
Script file node_modules/tinygradient error

### ISSUE THREAD

**Issue by PolarBearGod** [mitre-attack/attack-navigator#175]
Hello team,

Completely fresh install of both Docker, Node, and Angular/CLI.
When attempting to follow the directions on using Node to create the matrix, I am met with the following error:

`$ ng serve`   
> An unhandled exception occurred: Script file node_modules/tinygradient/tinygradient.js does not exist.  
> See "/private/var/folders/65/btbgpzgj2gjc5wp5mwkbtf3r0000gn/T/ng-5iXaYF/angular-errors.log" for further details.

I have validated I have installed tinygradient. Viewing the log, it shows (sanitized):

`cat /private/var/folders/65/btbgpzgj2gjc5wp5mwkbtf3r0000gn/T/ng-5iXaYF/angular-errors.log`

> [error] Error: Script file node_modules/tinygradient/tinygradient.js does not exist.  
    at /Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:150:19
    at Array.reduce (<anonymous>)  
    at Object.getCommonConfig (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:146:106)  
    at webpackPartialGenerator (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/browser/index.js:58:27)  
    at generateWebpackConfig (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:62:22)  
    at async generateBrowserWebpackConfigFromContext (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:137:20)  
    at async Object.generateI18nBrowserWebpackConfigFromContext (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:86:20)  
    at async setup (/Users/me/Downloads/attack-navigator/nav-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:103:47)

------
Thinking this might be an Angular issue I opted to just create a Docker container. I was again presented with the same error about tinygradient but Docker obviously reports its own errors:

`$ docker run -p 4200:4200 attackmatrix`

` \> nav-app@1.0.0 start /nav-app  
\> ng serve --host 0.0.0.0  

An unhandled exception occurred: Script file node_modules/tinygradient/tinygradient.js does not exist.  
See "/tmp/ng-qogbsi/angular-errors.log" for further details.  
npm ERR! code ELIFECYCLE  
npm ERR! syscall spawn  
npm ERR! file sh  
npm ERR! errno ENOENT  
npm ERR! nav-app@1.0.0 start: \`ng serve --host 0.0.0.0\`  
npm ERR! spawn ENOENT  
npm ERR!   
npm ERR! Failed at the nav-app@1.0.0 start script.  
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  

npm ERR! A complete log of this run can be found in:  
npm ERR!     /root/.npm/_logs/2020-06-11T16_22_10_345Z-debug.log`

Any assist or direction on where to go from here would be greatly appreciated.

**Comment by isaisabel** [comment]
Hi @PolarBearGod,

I've never actually seen an issue with TinyGradient before but it's possible something is odd with your install. Could you please provide us with the following information to help you debug:

1. Which branch are you on? 
2. What environment (e.g OS) are you running the application in?
3. Could you expand on what you mean by "I have validated I have installed tinygradient"? 
   - Did you run `npm install` from the `nav-app` folder to install requirements before running `ng serve`?
   - Could you please run from the `nav-app` directory `ls node_modules/tinygradient/` (if on OSX/Linux) or `dir node_modules\tinygradient\` (if on Windows) and provide us with the output? 

Thanks!

**Comment by PolarBearGod** [comment]
Hi @isaisabel ,
My apologies for the delays.

> Which branch are you on?  
Master. 
> What environment (e.g OS) are you running the application in?  
MacOS Catalina 10.15.5  
> Could you expand on what you mean by "I have validated I have installed tinygradient"?  
My apologies for the confusion here. Yes I followed the `nav-app` folder `npm install` method. When I saw the error, I manually installed tinygandient via `npm install tinygradient`. It presented some other information about my NPM instance but gave me the following information:

> + tinygradient@1.1.2  
> updated 1 package and audited 1847 packages in 9.194s


Running of `ls node_modules...` presents:  
>  $ ls node_modules/tinygradient/
> LICENSE			README.md		bower_components	package.json		tinygradient.d.ts	tinygradient.iml	tinygradient.js		tinygradient.min.js

-----

Update:  
So I removed the repo. Ran `npm audit fix`. Re-cloned, the repo. Re-ran `npm install` and now everything is loading correctly. Not sure what was going on but I am going to go ahead and close this issue.
