### ISSUE TITLE
Add support for mixed domains in a single ATT&CK Navigator instance

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#180]
As a user of the ATT&CK Navigator, I want to be able to open layers of multiple domains in a single instance.

- Refactor the hardcoded `enterprise`, `mobile` and `pre-attack` domains to make the list of domains definable in the config file.
- Allow the user to select the domain when opening a new layer
    - Each layer can only have one domain
- When uploading a layer, determine the domain data to use by the layer `domain` field
- Restrict layer-layer operations to layers of the same domain
- Lazy-load domain data. Load domain data only once a layer is opened with the given domain
- Refactor the layer `domain` field to use the ATT&CK convention:
    - `mitre-enterprise` becomes `enterprise-attack`
    -`mitre-mobile` becomes `mobile-attack`.
- Updated new-tab UI:
    ![image](https://user-images.githubusercontent.com/28868888/85406149-5e652a00-b52f-11ea-9d27-99a84f21ea31.png)

**Comment by nicolaipre** [comment]
I am looking for the exact same thing. Ideally, I would like every MITRE Matrix (https://attack.mitre.org/matrices/enterprise/) to be  available in a dropdown, such that if I select any Cloud Instances the non-relevant attack techniques disappear from my view. 

For example: If i select `Enterprise -> Cloud -> Azure`, it would be perfect if the view of MITRE navigator updated to only show the techniques listed for that matrix, like so: https://attack.mitre.org/matrices/enterprise/cloud/azure/

**Comment by isaisabel** [comment]
Hi @nicolaipre,

To some extent this feature already exists -- on the ATT&CK website, those sub-matrices within Enterprise (e.g the Azure matrix) are filtering techniques by platform. The filter feature on the Navigator allows you to replicate this same behavior:

![image](https://user-images.githubusercontent.com/28868888/94917729-197e5700-047f-11eb-89a0-a7e0382fd2d7.png)

What this issue is describing is allowing for mixed domains, e.g Enterprise and Mobile (and eventually ICS) inside of the same instance of the application. Currently each domain has its own instance like so:
- https://mitre-attack.github.io/attack-navigator/enterprise/
- https://mitre-attack.github.io/attack-navigator/mobile/

**Comment by nicolaipre** [comment]
@isaisabel Well, that was exactly what I was looking for. Not sure how I managed to miss out and not find that. But oh well.

Thank you for clarifying!

**Comment by isaisabel** [comment]
Staged on develop for the upcoming release.
