### ISSUE TITLE
T1557 Man-in-the-middle breaks "export to excel" function 

### ISSUE THREAD

**Issue by TheseArmsRSnakes** [mitre-attack/attack-navigator#186]
Use case: Wanted to view all _sub-techniques_ for _Linux_ in the _act_ stage. Applied appropriate filters then expanded all techniques. _Export to excel_  does not prompt save file. Collapsed _T1557 Man-in-the-middle_ box and _export to excel_ prompts save file. Tested on Firefox Browser Developer 78.0b9 and Iridium 2019.04. Json layer file zipped for upload and reproduction.

[navbug.zip](https://github.com/mitre-attack/attack-navigator/files/4834194/navbug.zip)

**Comment by isaisabel** [comment]
Hi @TheseArmsRSnakes,

We were able to reproduce the issue with the current beta (version 3.0) Navigator. However, it appears that the WIP version 3.1 Navigator doesn't have this bug. While we never explicitly touched the excel export feature in version 3.1, we did do a few refactors of the data handling which is probably what fixed the issue.

The version 3.1 Navigator will go live early next month with the sub-techniques release, but in the meantime you're welcome to check out the [feature/subtechniques-3.1](https://github.com/mitre-attack/attack-navigator/tree/feature/subtechniques-3.1) branch and run your own instance locally.
