### ISSUE TITLE
Search on description returns no results unless you unclick Name and Attack ID under properties searched 

### ISSUE THREAD

**Issue by scampb06** [mitre-attack/attack-navigator#200]
To reproduce the problem take the following steps.

1. Use Search Techniques within Selection Controls. Search for "ICMP" with all four "properties searched" selected. You get no results. 
2. Now unclick "Name" and "Attack ID" under "properties searched" and you will see two techniques - "Network Denial of Service:Direct Network Flood" and "Non-Application Layer Protocol".  
3. Similarly if you search for a specific "Attack ID" e.g. "T1095" with all four "properties searched" selected you get no results. 
4. When you unclick "Name" the technique "Non-Application Layer Protocol" appears.

**Comment by isaisabel** [comment]
This has been fixed in the [feature/v4.0](https://github.com/mitre-attack/attack-navigator/tree/feature/v4.0) branch. It will be released on master with the upcoming [v4.0](https://github.com/mitre-attack/attack-navigator/milestone/5) release.
