### ISSUE TITLE
Sort based on sub-techniques

### ISSUE THREAD

**Issue by marcusbakker** [mitre-attack/attack-navigator#201]
Hi team MITRE ATT&CK,

We noticed while generating layers that the sorting based on a score within the Navigator is only taking the "main" techniques into account. See for example the pictures below (I've also attached the layer file: [attack_windows_all.json.zip](https://github.com/mitre-attack/attack-navigator/files/4913113/attack_windows_all.json.zip)) where the technique T1203 has a score of 23 and the technique T1059 has a score of 11. However, the sub-technique T1059.001 has a score of 44 but does not end at the top.

Would it be possible to sort based on both the "main" and sub-techniques or provide this as an option? In my personal experience, this results in a better visual representation. It allows you to identify high scoring sub-techniques more easily. In particular, if the "main" technique has a very low score, but a sub-technique within this "main" technique has a high score. In the current version of the Navigator the latter sub-technique is ending up at the bottom. 

<img width="523" alt="T1023" src="https://user-images.githubusercontent.com/40516252/87316410-087c1480-c526-11ea-9b22-2325d1d7ffeb.png">
<img width="542" alt="T1059" src="https://user-images.githubusercontent.com/40516252/87316426-0c0f9b80-c526-11ea-96f4-ad695f1656ba.png">
<img width="467" alt="T1059 001" src="https://user-images.githubusercontent.com/40516252/87316419-0b770500-c526-11ea-8824-18e3a9eaf5fd.png">

Kind regards,
Marcus Bakker

**Comment by isaisabel** [comment]
Hi @marcusbakker,

This is a great idea! We'll probably have to change the sorting button to a dropdown to support the additional granularity (I'm not sure if this would be easy to represent with simply an icon). The new sorting options would be something like this:

- Alphabetically
    - ascending
    - descending
- By Score, excluding sub-techniques
    - Ascending
    - Descending
- By score, including sub-techniques
    - Ascending (using highest sub-technique)
    - Ascending (using lowest sub-technique)
    - Descending (using highest sub-technique)
    - Descending (using lowest sub-technique)

**Comment by marcusbakker** [comment]
Hi @isaisabel,

I'm very glad to hear you like the idea :-). Having such options in a drop-down would be great! I agree that having all these options within an icon becomes confusing. Will these options then also be available within the Layer file format?

I'm not sure though I fully understand the last part of the below options (between brackets). So, you can sort by the score in such a way that it will both include the techniques scores and sub-techniques scores. The exact part I'm missing right now. But, what is the effect of "using highest/lowest sub-technique"?

- Ascending (**using highest sub-technique**)
- Ascending (**using lowest sub-technique**)
- Descending (**using highest sub-technique**)
- Descending (**using lowest sub-technique**)

Regards,
Marcus

**Comment by isaisabel** [comment]
I may have overcomplicated it, but my intuition is that users might want to handle the scores of sub-techniques differently. Imagine a user is scoring according to coverage, where a higher score is more coverage. The user might want to sort as follows to explore their data:

- Descending (using highest sub-technique) to see what they have the most coverage of (AKA sort using `max(technique, sub-technique 1, sub-technique 2...)`
- Ascending (using lowest sub-technique) to see what they have the least coverage of (AKA sort using `min(technique, sub-technique 1, sub-technique 2...)`

I actually haven't been able to come up with a use case for the other two cases (ascending using highest sub-technique, descending using lowest sub-technique) but there _might_ be a use case which requires it. I need to think about whether those other two cases would actually be useful.

Does that make any sense?

**Comment by marcusbakker** [comment]
That's making sense @isaisabel :-)

**Comment by isaisabel** [comment]
Hi all,

This feature will be implemented via #269. If you have any feedback on the way we intend to implement it please let us know.

I'm closing this issue since it's superseded by #269.
