### ISSUE TITLE
Color technique according to sub-technique scores

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#202]
As a user of the ATT&CK Navigator, I want to be able to visualize technique color according to an aggregate of the sub-technique scores. For example, I want to be able to configure the application to show the technique color according to the min, max, or average of the technique score and sub-technique scores.

**Comment by Templar88** [comment]
One thing (as a user) I would add (in addition to min, max, and average) is total (sum) of the scores of the sub-techniques.

**Comment by isaisabel** [comment]
Hi all,

This feature will be implemented via #269. If you have any feedback on the way we intend to implement it please let us know.

I'm closing this issue since it's superseded by #269.
