### ISSUE TITLE
Inform the End User When Technique Users Change

### ISSUE THREAD

**Issue by AppGuard** [mitre-attack/attack-navigator#217]
Is there an efficient way to cross reference, or to be updated in some way, when Technique numbers change ?

For example, T1196 changed to T1196 to T1218.002. Now no one would have known that unless someone, luckily, just happened to look at the old MITRE website.

Is this really how end users are expected to keep track of Technique number changes ?

When a new version of the Navigator is released, the release notes don't even list the Technique number changes.

Really ?

**Comment by isaisabel** [comment]
Though the issue name differs, the content is the same as #216. I'm closing it as duplicate, but I can reopen it if there's something else you're trying to determine in this one.
