### ISSUE TITLE
Support for Multiple Comments

### ISSUE THREAD

**Issue by OpalSec** [mitre-attack/attack-navigator#219]
I have a Navigator Layer mapping techniques I've created detections for, with a brief comment for each technique stating what's covered, e.g. for T1068, it notes I've added Detections for the JuicyPotato" PrivEsc Technique.

Separately, as I find reporting on Actor activity and TTPs, I create/add to another layer mapping the techniques they've used.

I was hoping to be able to use [this reference](https://attack.mitre.org/docs/Comparing_Layers_in_Navigator.pdf) to compare known Actor TTPs with existing detections. While the comparison itself works, I'm unfortunately only able to have comments from either the detection layer, or Actor TTPs layer, when I really need both to give sufficient context when comparing the two sets.

Is it possible to render multiple comments in Navigator, or alternatively (not ideal) add the option to concatenate the comment fields with a ";" character when comparing two layers?

**Comment by isaisabel** [comment]
Hi @OpalSec,

While we don't technically support multiple _comments_, it is possible to add additional key:value pairs to a technique (or the layer itself) as [metadata](https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv3.md#metadata-object-properties). For example:
```json
{
    "techniqueID": "T1534",
    "tactic": "lateral-movement",
    "color": "#fca2a2",
    "comment": "",
    "enabled": true,
    "metadata": [
        {
            "name": "flower",
            "value": "daisy"
        },
        {
            "name": "legume",
            "value": "alfalfa"
        }
    ],
    "showSubtechniques": false
}
```

Which looks like this in the UI:
![image](https://user-images.githubusercontent.com/28868888/91039816-3fd8e900-e5db-11ea-9760-df60168562ae.png)

We also have plans to add additional features to these custom fields (see #189).

Unfortunately, at present metadata cannot be added from the UI, it can only be added in the downloaded JSON.

**Comment by OpalSec** [comment]
That's perfect for my needs, thanks for flagging this!
