### ISSUE TITLE
Multiple Tabs in iframeURL loads one URL twice

### ISSUE THREAD

**Issue by OpalSec** [mitre-attack/attack-navigator#220]
I have followed [steps outlined here](https://mitre-attack.github.io/attack-navigator/enterprise/#help_Customizing_The_Navigator) sAnd generated a URL using the "Create Customized Navigator" option, adding in two URLs that I wanted it to open on launch, which were two different json layers hosted on the same local instance of Navigator.

```
<iframe src="https://navigator.local/#layerURL=https://navigator.local/assets/heatmap_Actor1.json&layerURL=https://navigator.local/assets/comparison_Actor1_Actor2.json" width="1850" height="1380"></iframe>
```
Both files exist, contain the correct content, and are accessible to Navigator. However when I open the link (either directly in a browser or via the iframe), the second layer (comparison_Actor1_Actor2.json) is opened twice, and the heatmap isn't opened at all.

I've confirmed the json exists in both those locations and is accessible to Navigator when opened directly, it just doesn't seem to work when I'm attempting to have it open by using the layerURL URL fragment. 

Noting that the URL was generated by Navigator (I just copied and pasted it into the iframe), can you see if you can reproduce this? I can't think of anything I can do differently on my end to fix this.

**Comment by isaisabel** [comment]
Hi @OpalSec,

I'm pretty sure this is the same bug as #199. If so, it will be fixed in the next release, which you can preview in the [feature/v4.0](https://github.com/mitre-attack/attack-navigator/tree/feature/v4.0) branch if you're so inclined.

**Comment by isaisabel** [comment]
Version 4.0, which includes a fix for this bug, has been released today.
