### ISSUE TITLE
Option for a single font size on SVG export

### ISSUE THREAD

**Issue by johnwunder** [mitre-attack/attack-navigator#221]
Recently, the font sizing in the SVG export for the navigator became dynamic, where the text in each cell is auto-fitted and the font size varies between cells. While that can improve readability, it reduces visual consistency and can look off-putting. Could the option to have a single, manually set, font size be added back? Or, even better, the option to use the largest size that fits all text in all boxes across the board.

**Comment by clemiller** [comment]
Changes for this issue are currently staged on develop ([#394](https://github.com/mitre-attack/attack-navigator/pull/394)) and will be included in the next Navigator v4.5.5 release.
