### ISSUE TITLE
Will MITRE ATT&K ICS be added to the navigator?

### ISSUE THREAD

**Issue by KyyB** [mitre-attack/attack-navigator#229]

**Comment by isaisabel** [comment]
Hi @KyyB,

The ICS domain is not currently integrated into the greater ATT&CK infrastructure (thus its inclusion on a separate wiki). As it matures we may eventually move it over to the primary infrastructure, which would include the ATT&CK Navigator. We don't have any information on the timeframe of this integration at this moment.

**Comment by isaisabel** [comment]
Duplicate of #126.

**Comment by isaisabel** [comment]
Hi @KyyB,

Just wanted to quickly update you that ICS is now supported in the Navigator as of version 4.0.
