### ISSUE TITLE
Sort by Score not Applying to SVG Render

### ISSUE THREAD

**Issue by tavalkyansant** [mitre-attack/attack-navigator#244]
Hello,

Recently, (approx last two weeks) sorting by score (descending, or ascending - difference does not matter) does not appear to translate over to the SVG render. For example:

In Navigator View:
![example_ss](https://user-images.githubusercontent.com/68788972/97228686-303e7200-17cf-11eb-8dab-b88a9588c700.png)

Render Output:
![image](https://user-images.githubusercontent.com/68788972/97228922-7d224880-17cf-11eb-8d60-01f85c91753e.png)

Browsers tested:
Firefox 82.0 (64-bit)
Chromium Version 87.0.4249.0 (Developer Build) (64-bit)

Repeatability: 100% of the time, have not verified on additional hosts as they are not available to me.

Issue occurs both local and within the online instance of the web app.

Up until recently, there was no issue and I was able to successfully have the render be sorted by score. 

Thank you

**Comment by isaisabel** [comment]
Hi @tavalkyansant,

This bug has already been fixed in #223 which is part of the version 4.0 update. Version 4.0 will be released onto the live instance very soon, but in the meantime you should be able to check it out on the develop branch.

Thanks!
