### ISSUE TITLE
Comment issue

### ISSUE THREAD

**Issue by younessmz** [mitre-attack/attack-navigator#255]
Some techniques won't display the comment in the comment section dropdown. On one technique for some json it works you can dropdown the comment on the up right corner of the navigator and it will display, but for other json on the same technique even if there is a comment the dropdown comment will be blank.

**Comment by isaisabel** [comment]
Hi @younessmz,

I'm having trouble reproducing this issue. Can you upload the a layer with this issue is occuring to help us debug? Also if you could provide specific steps to reproduce (e.g "click internal spearphishing in lateral movement, then click the comment button...").

Thanks!

**Comment by younessmz** [comment]
[comment_testing.zip](https://github.com/mitre-attack/attack-navigator/files/5702952/comment_testing.zip)

Here is a zip of a json where I reproduced the issue.

If I select the technique "Valid Account" then click on the comment button, the comment will be displayed under the comment button.

If I select Scheduled Task/Job in the Persistence tactic and then click on the comment button the comment section will be blank even though there is a comment and I can see it whilst moving the mouse on the technique itself.

(It causes an issue for very long comment where we need to click on the comment button to be able to read through it.)

Thanks for your reactivity !

**Comment by younessmz** [comment]
I figured it out it seems to be the fact that one of the multiple technique selected does not have the same comment so it won't display anything. I just have to disable multi-selection and then select the one technique I am interested in.
