### ISSUE TITLE
Error with node and/or Angular

### ISSUE THREAD

**Issue by waynevillars** [mitre-attack/attack-navigator#258]
I tried following the instructions to install navigator via Docker on an Ubuntu EC2 instance, but something involving node and/or angular failed. I apologize for lack of detail, but I know nothing about either one of those things. I've attached a terminal transcript so you can see the errors, as well as a screenshot of what I see when I try to browse to the navigator.

[attack navigator install failure log.txt](https://github.com/mitre-attack/attack-navigator/files/5770076/attack.navigator.install.failure.log.txt)

![Screenshot 2021-01-05 070907](https://user-images.githubusercontent.com/27702789/103645804-99a4d480-4f26-11eb-99e9-7d11afe5cec3.png)

**Comment by beerMT** [comment]
Bumping - getting the same issue doing the docker install.

Numerous *Module errors are reported and then StdOut shows - ** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

When you navigate to localhost:4200 it has the error as shown in the screen shot above. Port (-p) passed to container on startup is the same.

**Comment by isaisabel** [comment]
Hi all,

We've observed a similar (or possibly parallel) issue when building the Navigator outside of docker, but with outdated versions of Angular installed (we upgraded Angular from v7 to v11 in the v4.1 release). The solution in that case is to remove node_modules and reinstall to ensure the correct version of Angular is installed.

Have either of you used the Navigator through docker previously? I'm wondering if a previous install may be affecting the new build.

**Comment by waynevillars** [comment]
Yes, we had previously built Navigator through docker and it worked fine. We were trying to upgrade, which is what brought this all about. We initially tried to just build a new Navigator docker image on the original machine. When that failed, we thought the same thing as you (that a previous installation was causing problems), so we blew the old machine away (meaning the entire VM/EC2 instance) and started with a new one, but we ran into the same issue.

**Comment by isaisabel** [comment]
Good to know, thanks. We are prioritizing #257/#251 since that affects the live instance, but we'll look into this afterwards.

**Comment by jberry777** [comment]
I haven't updated since December 15th 2020. That dockerized Navigator is still operational. 
However, today I tried to build Navigator locally through docker to test new layers I built and encountered the same errors as described in the initial post above. The first error prompted me to update to the newest npm version (7.3.0 -> 7.4.1) but when rebuilding I encountered the same errors.

**Comment by isaisabel** [comment]
Hi all,

This issue has been addressed in #258 and docker is now working on the develop branch. We'll be releasing Navigator v4.2 (which includes this fix) later this week, but you're welcome to use the develop branch until then if desired.
