### ISSUE TITLE
This site can't be reached issues

### ISSUE THREAD

**Issue by wearenotsecure** [mitre-attack/attack-navigator#264]
Just followed the instructions to have the launch the navigator locally and i have hit an issue where i cannot access the navigator from other machines on the network . 
 I can confirm it works locally ( doing a curl gives me the html code.. ) however when i try to access it from another host on the network i get the "This site can't be reached" error . I have turned off the firewall completely to make sure that is not interfering , i know connectivity between these 2 hosts does work as i am running another web app on another port which is working fine. 
 I suspect the issue is with nodejs/angular listening only on 'localhost' but i cannot find where to change this , can anyone help ?

**Comment by isaisabel** [comment]
Hi @wearenotsecure,

I'm not quite sure what's causing your issue, but it's possible that `ng serve` is not designed for live instances accessible from multiple hosts. You may want to consider using `ng build` to build the static files and hosting them with a different webserver (nginx for example). 

You could also try looking [here](https://github.com/angular/angular-cli/issues/2542). I've not tested it but it seems to be describing the same issue.

**Comment by wearenotsecure** [comment]
Hi @isaisabel 
 Thanks for that, the link had the info i needed . Incase anyone else has the same issue the way i fixed it was by running "ng serve --host=xxx.xxx.xxx.xxx  ( host ip address )
