### ISSUE TITLE
Custom context variable substitution is not global

### ISSUE THREAD

**Issue by gclen** [mitre-attack/attack-navigator#265]
First off, this project is amazing and thanks for all your hard work! When adding a custom context label only the first instance of a variable is substituted. For example if you had

```http://www.someurl.com/{{technique_attackID}}}/otherstuff/{{technique_attackID}}```

it would become

```http://www.someurl.com/T1234/otherstuff/{{technique_attackID}}```

not 

```http://www.someurl.com/T1234/otherstuff/T1234```

I have a pull request which fixes this coming soon.

**Comment by isaisabel** [comment]
Addressed in #266 and merged into develop. Will be released to Master with Navigator v4.3.
