### ISSUE TITLE
Aggregate Scores

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#269]
As a user, I want to be able to:
- Sort based on sub-techniques (#201)
- Color techniques according to sub-techniques (#202)

Pursuant to these objectives, the Navigator should be extended with the concept of an Aggregate Score. Aggregate scores only occur on techniques, not sub-techniques, and take into account the score of both the technique and sub-techniques. Aggregate scores are computed using an _aggregation function_, which is a mathematical expression determining how the aggregate score is assigned. For example:
- min
- max
- average
- sum

When enabling the aggregation score, the user should be able to select the aggregation function from the above list. The aggregate score is then computed for each technique according to their selection. When scores are changed for the technique or any of its sub-techniques, the aggregate score is re-computed using the aggregation function.

Aggregate scores, if present, are used for sorting and coloring of techniques instead of normal scores. They also should be shown in the tooltip (in an additional row adjacent to the score marked "aggregate score").

**Comment by isaisabel** [comment]
Note: sub-techniques (or techniques) without scores should not be considered within the aggregation function. In other words, if a you have the following:
- T1000 (score: 5)
    - T1000.001 (score: 1)
    - T1000.002 (score: 1)
    - T1000.003 (no score)
    - T1000.004 (score: 1)

The `average` aggregation function would return 7.25 (`(5+1+1+1)/4`) since `T1000.003` has no score.

**Comment by marcusbakker** [comment]
Hi Isabel,

Would the aggregation function also take into account the platform filtering to include or exclude specific techniques?

I can understand why you want to exclude "main" techniques in the aggregation without a score. But wouldn't it make sense always to include a no score for a sub-technique? Or can I force the aggregation to include those by assigning a score of 0?

Regards,
Marcus

**Comment by isaisabel** [comment]
Hi @marcusbakker,

> Would the aggregation function also take into account the platform filtering to include or exclude specific techniques?

That's a good point, yes I think it would not take into account any hidden (sub-)techniques. That would include platform filtering and disabled + hidden (sub-)techniques. Otherwise the user might get confused regarding the result of the aggregation if some of the contributing scores are not visible in the view. We will need to make this clear in the documentation however.

> I can understand why you want to exclude "main" techniques in the aggregation without a score. But wouldn't it make sense always to include a no score for a sub-technique? Or can I force the aggregation to include those by assigning a score of 0?

My idea here is that sometimes a user may want to exclude a sub-technique from being considered in the aggregation function (e.g if it's "out of scope" or unmapped, and they only wanted to account for in-scope/mapped sub-techniques). 
Maybe we should add an additional control, "include unscored sub-techniques," which if enabled includes unscored sub-techniques in the aggregation function with the default value of 0.

**Comment by marcusbakker** [comment]
Hi Isabel,

> That's a good point, yes I think it would not take into account any hidden (sub-)techniques. That would include platform filtering and disabled + hidden (sub-)techniques. Otherwise the user might get confused regarding the result of the aggregation if some of the contributing scores are not visible in the view. We will need to make this clear in the documentation however.

That would be great to have this being taken into account :smile:.

> My idea here is that sometimes a user may want to exclude a sub-technique from being considered in the aggregation function (e.g if it's "out of scope" or unmapped, and they only wanted to account for in-scope/mapped sub-techniques).
Maybe we should add an additional control, "include unscored sub-techniques," which if enabled includes unscored sub-techniques in the aggregation function with the default value of 0.

Ok, I get it now. I would be a big fan of having the control "Include unscored sub-techniques".

Just to be sure, let me explain further. Having the ability to include unscored sub-techniques will provide a more accurate view of, for example, your detection coverage. The below would result in an average score of 3 instead of 2.25 when unscored sub-techniques are included. The latter (at least in the way I'm using it) would be more accurate as having a detection for T1000.03 (with a score of X) will further improve my overall detection coverage for T1000.

* T1000 (no score)
  * T1000.001 (score: 2)
  * T1000.002 (score: 3)
  * T1000.003 (score: 0)
  * T1000.004 (score: 4)

**Comment by beerMT** [comment]
So many up votes for this scoring discussion - been trying to wrap my head around this for a minute! Very well articulated in this issue - I'll be following along. Cheers!

**Comment by isaisabel** [comment]
Implemented in #274 and staged on develop.
