### ISSUE TITLE
Running stand-alone attack-navigator

### ISSUE THREAD

**Issue by rporterlv** [mitre-attack/attack-navigator#273]
The navigator runs great as a stand-alone on port 4200.  Is there anyway to run it on another port?.  I have modified the Dockerfile, as well as the port in /nav-app/protractor.conf.js.  Is there somewhere else I'm missing?

Thanks

**Comment by isaisabel** [comment]
Hi @rporterlv,

You can use the `--port` argument of [ng serve](https://angular.io/cli/serve) to change the port, e.g `ng serve --port 8080`.

You can also use `ng build` to build the application to a static set of HTML/CSS/JS files and host them on the web server of your choosing.
