### ISSUE TITLE
Question: Running Navigator on Github Pages (forked)

### ISSUE THREAD

**Issue by SanWieb** [mitre-attack/attack-navigator#275]
Hi,

I would like to run an attack-navigator instance on Github Pages or Azure Storage. How do I have to setup the actions / Github Pages?
When I fork the project and enable GitHub pages on the root, the main page on the website is the README.md. Browsing to {base_url}nav-app/src/ results in a white page.

Thanks in advance!

**Comment by isaisabel** [comment]
Hi @SanWieb,

The code on this repo is the raw source code used to build the app. GitHub pages is designed to serve static HTML, CSS and Javascript files, not the Angular source code. So what you'll need to do is follow the [compile for use elsewhere](https://github.com/mitre-attack/attack-navigator#compile-for-use-elsewhere) instructions to compile the application and then copy the resultant files from `nav-app/dist` to the root of your GitHub pages instance.

For what it's worth, the live instance we host at https://mitre-attack.github.io/attack-navigator/ is also served using GitHub pages, so you can check out exactly what's being served on the [gh-pages](https://github.com/mitre-attack/attack-navigator/tree/gh-pages) branch of this repo. We have a few extra things there (older versions of the application, some redirects from prior enterprise/mobile instances, google analytics), but the gist of it should be the same.

Let me know if you run into any further trouble getting it set up!
