### ISSUE TITLE
Add support for TAXII 2.1

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#277]
As a user of the ATT&CK-Navigator, I want to be able to load STIX 2.1 data from a TAXII 2.1 server.

This will require changes to [taxii2lib.ts](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/taxii2lib.ts), and likely also additions to the config format to specify the TAXII version when TAXII is used.

**Comment by clemiller** [comment]
Changes staged on `develop`
