### ISSUE TITLE
Attack-navigator use fonts.googleapis.com

### ISSUE THREAD

**Issue by 2xyo** [mitre-attack/attack-navigator#278]
The attack-navigator app download the fonts from fonts.googleapis.com.

https://github.com/mitre-attack/attack-navigator/blob/5b6dbf918d186afaf899f1102305aceb8f4cc6c7/nav-app/src/app/tabs/tabs.component.html#L1

A good thing would be to download the fonts from the server of the attack-navigator app. This way, an "off-grid" attack-navigator app  won't need to get external sources to function properly.

Proposed fix (no tested):

```
npm install @fontsource/roboto
```
And update `/nav-app/src/styles.scss`
 ```
@import "~@fontsource/roboto/500.css";
```

**Comment by isaisabel** [comment]
Issue was fixed in #280. Will be released alongside Navigator v4.4.
