### ISSUE TITLE
When opening multiple default layers, the second one only shows up after the first has been moused-over

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#288]
When loading multiple default layers either through the config file or layerURL, the second layer will only show up once the user has moused over a cell in the first matrix. 

Steps to reproduce:
1. Open the Navigator with multiple default layers specified (e.g [this one](https://mitre-attack.github.io/attack-navigator/#layerURL=https%3A%2F%2Fraw.githubusercontent.com%2Fmitre-attack%2Fattack-navigator%2Fmaster%2Flayers%2Fdata%2Fsamples%2FBear_APT.json&layerURL=https%3A%2F%2Fraw.githubusercontent.com%2Fmitre-attack%2Fattack-navigator%2Fmaster%2Flayers%2Fdata%2Fsamples%2Fheatmap_layer.json))
2. If the layers are out of date (like the link above), press enter to accept the warning without using the mouse. In the example linked to above, both layers will produce a warning.
3. The second layer will not be shown in the UI at all as long as your mouse doesn't pass over a technique cell.
4. Mouse-over a cell in the matrix. The second layer will now be selected and shown.

**Comment by isaisabel** [comment]
https://user-images.githubusercontent.com/28868888/115768908-ee0a7d80-a378-11eb-8609-1eeae318ee83.mov

**Comment by lilyjw** [comment]
Have a small async fix for this, see behavior below with no mousing over elements. 

Q: Is this behavior with the last-loaded default layer as active desired?  My default layers are ordered in importance, so would be interested in the first one as active, but can always reverse order the files in config.


https://user-images.githubusercontent.com/1416347/123109957-aa300500-d409-11eb-8a8d-9604123f53b4.mov

**Comment by isaisabel** [comment]
I don't think the order of default layers is specified anywhere in the docs, I believe they just open in the order they're defined as a result of [the implementation of that feature](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/tabs/tabs.component.ts#L99-L105). 

If you have a fix that you're willing to share we encourage you to open a pull request targeting the develop branch so that it can be integrated into the codebase for the betterment of all users of the application.
