### ISSUE TITLE
Sort by highest score appears to be broken

### ISSUE THREAD

**Issue by beerMT** [mitre-attack/attack-navigator#295]
I love the roll-up (sum) of SubTechniques into the Techniques score, thanks for that update!

When sorting by most frequently occurring Technique, the following was the result:
<img width="1864" alt="sorted_butNot" src="https://user-images.githubusercontent.com/6117308/117991332-2e677680-b2fb-11eb-8b59-af7bfab4d11c.png">

I have "hotter" red items that did not bubble up. Any help here on regaining that functionality would be great.

Cheers,
Brad

**Comment by isaisabel** [comment]
Hi @beerMT,

Is there any chance you can upload the layer you're using so that we can use it to debug? I'm having a bit of trouble reproducing the issue.

**Comment by beerMT** [comment]
Thanks for taking a look. I have attached a test merged layer, which consists of roughly 33 TA's merged together that target a test industry. The Techniques/Subtechniques were added together/incremented if present in the jsons. This was the layer that produced the output heatmap for opening the issue.

[merged_test.json.zip](https://github.com/mitre-attack/attack-navigator/files/6495468/merged_test.json.zip)

**Comment by iguannalin** [comment]
Hi @beerMT,

Thanks for sharing that json file. You're right, I see that the colors are being calculated correctly, but it does not seem to be sorting by the aggregate score correctly when that's enabled. We should create this as an issue.

**Comment by isaisabel** [comment]
This issue is now fixed on develop and will be released with Navigator v4.4.
