### ISSUE TITLE
Start attack-navigator as daemon/service

### ISSUE THREAD

**Issue by ezaspy** [mitre-attack/attack-navigator#317]
From following the Install and Run instructions (https://github.com/mitre-attack/attack-navigator#serve-application-on-local-machine) it says to run `ng serve` for the app to be available on `localhost:4200` but after doing so I cannot use my terminal window without killing the process serving the attack-navigator app.

I want to stand up an instance of attack-navigator as part of a script but when I get to the `ng serve` command, it hangs...
How can I run `ng serve` as a background process?

**Comment by isaisabel** [comment]
Hi @ezaspy,

The [screen](https://linux.die.net/man/1/screen) command can be used for this. I believe is available by default in Linux and OSX without additional installations. On Windows you could use [Cygwin](https://www.cygwin.com/) which _should_ give you access to the same command, or find an alternative tool like screen for the windows command line (I'm not as familiar with approaches to this issue for Windows).

For screen:
1. Launch a new screen with `screen`
2. Serve the application with `ng serve`
3. Disconnect from the screen: `CTRL+a` and then (without CTRL) `d`
4. When you want to reconnect to the screen (to later stop the running process), run `screen -r` to reattach.

**Comment by ezaspy** [comment]
Thank you! How do invoke CTRL for the CTRL + A from a script?

**Comment by isaisabel** [comment]
I'm not quite sure to be honest. I would think the entire script would need to be run in the screen, and you'd exit manually after starting it? 

If you were trying to launch the Navigator as part of a larger workflow you may also be able to achieve that by building it as a docker container (see the provided dockerfile). Alternatively, you can build the Navigator as static files and host them using an HTTP server of your choice -- there should be plenty of solutions for what you're trying to do for generic HTTP servers like Apache.

**Comment by ezaspy** [comment]
I have copied the nav-app/dist directory to my apache2 directory and have started apache2 but the attack-navigator page doesn't display anything...
Only the page title on the browser tab shows 'ATT&CK (R) Navigator' but there is nothing on the page

**Comment by isaisabel** [comment]
Can you share the contents of your javascript console? Any errors would be displayed there.

**Comment by ezaspy** [comment]
I'm not using a JavaScript console. I'm using a python script to invoke Terminal commands on Linux and copy the directory to my apache web server location

**Comment by isaisabel** [comment]
Sorry, I should have been more specific. I mean the browser's javascript console (where you're viewing the application). 

### In Firefox:
Tools -> Browser Tools -> Browser Console

### In Chrome:
View -> Developer -> Javascript Console

**Comment by isaisabel** [comment]
It should look like something like this (but with probably a bunch of errors in your case):

### Firefox:
![image](https://user-images.githubusercontent.com/28868888/125084985-17919600-e098-11eb-8c0a-f2e48eba081f.png)

### Chrome:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/28868888/125085069-2f691a00-e098-11eb-9a4a-c61ccc04a9db.png">

**Comment by ezaspy** [comment]
Apologies - my bad. This is what I have (I this is what you mean):
![Screenshot 2021-07-09 at 14 38 41](https://user-images.githubusercontent.com/42219366/125086265-5c7ef200-e0c3-11eb-9339-dbc2acdf36be.png)

**Comment by isaisabel** [comment]
The second image is the correct one. It looks like your browser is blocking the necessary Javascript files from being loaded since they're being seen as `text/html`. My guess is apache2 is serving them as if they're HTML but the browser knows they're actually javascript and is therefore blocking them.

You probably need to tell apache that it should serve them as javascript. [Something like this may help?](https://stackoverflow.com/questions/19652890/my-scripts-and-styles-get-served-as-text-html) I'm not super familiar with apache configuration myself.

**Comment by isaisabel** [comment]
I believe this is the documentation for how to configure that in apache: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Apache_Configuration_htaccess#serve_resources_with_the_proper_media_types_a.k.a_mime_types

**Comment by isaisabel** [comment]
You may also need to add CSS to the allowed types if page content shows up but looks off.

**Comment by ezaspy** [comment]
I've added the following line to my apache2

**AddType text/javascript           js mjs**

```
...
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        AddType text/javascript           js mjs
</Directory>
...
```

But still showing the same errors

**Comment by ezaspy** [comment]
This has solved it for me!
https://stackoverflow.com/questions/59925804/blocked-because-of-a-disallowed-mime-type-text-html-angular-8-deployed-on
