### ISSUE TITLE
Open Layer -> ERROR: Either the file is not JSON formatted, or the file structure is invalid.

### ISSUE THREAD

**Issue by ezaspy** [mitre-attack/attack-navigator#319]
I am running an apache2 server which is hosting attack-navigator but when I attempt to open a saved layer (which is valid because I've loaded it here: https://mitre-attack.github.io/attack-navigator/) i get the following error (also screenshot attached): **_ERROR: Either the file is not JSON formatted, or the file structure is invalid._** In a pop-up window.
<img width="943" alt="Screenshot 2021-07-11 at 09 03 42" src="https://user-images.githubusercontent.com/42219366/125189355-966d0700-e22f-11eb-9e10-af93a1e96ed5.png">

I think I have configured my apache2 server to server json file...
<img width="375" alt="Screenshot 2021-07-11 at 09 46 34" src="https://user-images.githubusercontent.com/42219366/125189348-910fbc80-e22f-11eb-8720-79a2c59df02f.png">

I have attached an archive of the following files for you to review the content:
index.html; config.json; casetest.json (my custom JSON file which cannot be opened)
[Error_JSON.zip](https://github.com/mitre-attack/attack-navigator/files/6796611/Error_JSON.zip)

**Comment by isaisabel** [comment]
Hi @ezaspy,

This is because of your modifications to the config file and not an issue with the layer file itself. From the `config.json` file you attached to the issue it looks like you're trying to load the `casetest.json` as data for the Enterprise domain. Data used as input in the `domains` structure should be [STIX 2.0 or STIX 2.1 formatted JSON](https://stixproject.github.io/about/), not layer files. To load your casetest as a default layer you only need to specify it in `default_layers` as I see you've done. 

You shouldn't need to edit the `domains` structure at all for most deployments of the application. The only cases you'd need to modify that structure would be the following:
1. You want to run the Navigator without internet access. See [running the Navigator offline](https://github.com/mitre-attack/attack-navigator#running-the-navigator-offline) for instructions on how to do this correctly.
2. You want to load a custom matrix into the Navigator (with new/adjusted techniques, tactics, etc). This is not the same as a layer, which should be understood as a set of annotations on top of the matrix itself. For this case you would put your custom STIX in the assets folder and modify your config file as noted in the [loading content from local files](https://github.com/mitre-attack/attack-navigator#Loading-content-from-local-files) instructions.

So assuming you don't need either of those use cases you should be able to reset the `domains` structure to default and it should start working.

**Comment by ezaspy** [comment]
Thank you @isaisabel but I am still experiencing the same issue. I have attached my updated files from your review.
I am actually trying to run Navigator without a connection to the internet so I have (hopefully) integrated those adjustments as you have described
[casetest.zip](https://github.com/mitre-attack/attack-navigator/files/6803975/casetest.zip)
.

**Comment by isaisabel** [comment]
That's still not the correct formatting for the config. I think you also very likely have the wrong paths for your assets -- they're according to how the pages are hosted via Apache2, not their absolute path on the machine -- the Navigator retrieves them (the ATT&CK data and the default layers) over HTTPs, not from the filesystem itself.

Here's what I _think_ you need:

```json
{
    "versions": [
        {
            "name": "ATT&CK v9", 
            "domains": [
                {   
                    "name": "Enterprise", 
                    "data": ["assets/enterprise-attack.json"]
                }
            ]
        }
    ],

    "custom_context_menu_items": [

    ],

    "default_layers": {
        "enabled": true,
        "urls": ["assets/casetest.json"]
    },

    "comment_color": "yellow",

    "banner": "",

    "features": [
        {"name": "leave_site_dialog", "enabled": true, "description": "Disable to remove the dialog prompt when leaving site."},
        {"name": "tabs", "enabled": true, "description": "Disable to remove the ability to open new tabs."},
        {"name": "selecting_techniques", "enabled": true, "description": "Disable to remove the ability to select techniques."},
        {"name": "header", "enabled": true, "description": "Disable to remove the header containing 'MITRE ATT&CK Navigator' and the link to the help page. The help page can still be accessed from the new tab menu."},
        {"name": "subtechniques", "enabled": true, "description": "Disable to remove all sub-technique features from the interface."},
        {"name": "selection_controls", "enabled": true, "description": "Disable to to disable all subfeatures", "subfeatures": [
            {"name": "search", "enabled": true, "description": "Disable to remove the technique search panel from the interface."},
            {"name": "multiselect", "enabled": true, "description": "Disable to remove the multiselect panel from interface."},
            {"name": "deselect_all", "enabled": true, "description": "Disable to remove the deselect all button from the interface."}
        ]},
        {"name": "layer_controls", "enabled": true, "description": "Disable to disable all subfeatures", "subfeatures": [
            {"name": "layer_info", "enabled": true, "description": "Disable to remove the layer info (name, description and metadata) panel from the interface. Note that the layer can still be renamed in the tab."},
            {"name": "download_layer", "enabled": true, "description": "Disable to remove the button to download the layer."},
            {"name": "export_render", "enabled": true, "description": "Disable to remove the button to render the current layer."},
            {"name": "export_excel", "enabled": true, "description": "Disable to remove the button to export the current layer to MS Excel (.xlsx) format."},
            {"name": "filters", "enabled": true, "description": "Disable to remove the filters panel from interface."},
            {"name": "sorting", "enabled": true, "description": "Disable to remove the sorting button from the interface."},
            {"name": "color_setup", "enabled": true, "description": "Disable to remove the color setup panel from interface, containing customization controls for scoring gradient and tactic row color."},
            {"name": "toggle_hide_disabled", "enabled": true, "description": "Disable to remove the hide disabled techniques button from the interface."},
            {"name": "layout_controls", "enabled": true, "description": "Disable to remove the ability to change the current matrix layout."},
            {"name": "legend", "enabled": true, "description": "Disable to remove the legend panel from the interface."}
        ]},
        {"name": "technique_controls", "enabled": true, "description": "Disable to disable all subfeatures", "subfeatures": [
            {"name": "disable_techniques", "enabled": true, "description": "Disable to remove the ability to disable techniques."},
            {"name": "manual_color", "enabled": true, "description": "Disable to remove the ability to assign manual colors to techniques."},
            {"name": "scoring", "enabled": true, "description": "Disable to remove the ability to score techniques."},
            {"name": "comments", "enabled": true, "description": "Disable to remove the ability to add comments to techniques."},
            {"name": "clear_annotations", "enabled": true, "description": "Disable to remove the button to clear all annotations on the selected techniques."}
        ]}
    ]
}
```

You can test whether the paths are correct by pointing your web browser to `http://localhost/assets/enterprise-attack.json` and `http://localhost/assets/casetest.json`.

**Comment by ezaspy** [comment]
Yes! You thought correctly @isaisabel, that works! thank you so much!
