### ISSUE TITLE
Scrolling of long comment is not easy to handle

### ISSUE THREAD

**Issue by bip2fois** [mitre-attack/attack-navigator#320]
scrolling through a long comment field with the mouse wheel is a bit difficult.

Scrolling down is manageable in one go.

Back and forth up and down is impossible.

https://user-images.githubusercontent.com/87380145/125478632-a34e6ebb-bd01-4d47-a36b-21069d78c44d.mp4

**Comment by isaisabel** [comment]
The video you attached doesn't seem to work. Are you talking about the comment input field in the toolbar, or the comment display in the tooltip?

UI support for long comments has always been a bit shaky in the Navigator so I can definitely understand if you're having trouble with it.

**Comment by clemiller** [comment]
A new option to `pin/unpin the tooltip` has been added to the context menu (accessed by right-clicking a technique). After clicking on this option, the tooltip will remain open without requiring the mouse to stay hovered over the technique cell and allows the ability to scroll through a long tooltip. This has been merged into `develop` and will be included in the next Navigator release.
