### ISSUE TITLE
Export the created layer as URL...

### ISSUE THREAD

**Issue by StealerCook** [mitre-attack/attack-navigator#328]
Is there a way to export the layer created by me as an URL and share the same to others?

**Comment by isaisabel** [comment]
Hi @StealerCook,

Unfortunately that is not possible with the ATT&CK Navigator. We did actually consider this in the initial development effort, but unfortunately there are length limits for query strings on most browsers which would preclude storing a layer file.

There is a way around this however. You can upload the layer to a GitHub repository and use the "create a customized navigator" interface to [add a default layer](https://github.com/mitre-attack/attack-navigator/blob/develop/USAGE.md#default-layers) by specifying that URL. 

You can also do this with a GitHub Gist if you don't want to create a full repository. Gists can be set to "secret" (so they won't be seen by google or show up on the master Gist list) which can help you control access, but it's not a perfect solution and I would not trust that for layers containing sensitive information. Here's how to do that step-by-step:
1. Go to [gist.github.com](gist.github.com) and create a new Gist containing the layer
   ![Screen Shot 2021-08-04 at 7 46 19 AM](https://user-images.githubusercontent.com/28868888/128175789-1b466a8e-631b-4044-b238-172f555d2172.png)
2. Go to the "raw" version of the gist and copy the URL
   ![Screen Shot 2021-08-04 at 7 46 29 AM](https://user-images.githubusercontent.com/28868888/128175854-dc3f9e65-55ba-4346-bae7-909976a086e4.png)
3. Enter the raw URL as the layer link in the Navigator
   ![Screen Shot 2021-08-04 at 7 48 37 AM](https://user-images.githubusercontent.com/28868888/128175936-78d48312-c746-44e3-b808-3b53a97bad95.png)
4. Copy the resultant custom layer link and share it with whomever you want to be able to access that layer
   ![Screen Shot 2021-08-04 at 7 48 55 AM](https://user-images.githubusercontent.com/28868888/128175987-ff7c3356-fdb5-4c7c-a338-e87585a6db7f.png)

For reference here's the data I used in the above example:
- [The Gist I created](https://gist.github.com/isaisabel/105c83518747d963b0e069865aa7b22c)
- [The customized Navigator URL which loads the layer from the Gist](https://mitre-attack.github.io/attack-navigator/#layerURL=https%3A%2F%2Fgist.githubusercontent.com%2Fisaisabel%2F105c83518747d963b0e069865aa7b22c%2Fraw%2F01a037c41788d4dc19643622d38e3743f4967c55%2Fgithub-gist-example.json)

Again, while "secret" (unlisted) the Gist can still be accessed by anyone with the link so this methodology is not suitable for layers containing sensitive information. If your layer file(s) have sensitive information I would recommend sharing the layer JSON directly and not uploading it anywhere on the internet for use with the customized Navigator feature.
