### ISSUE TITLE
Options in exporting the created layer as URL.

### ISSUE THREAD

**Issue by StealerCook** [mitre-attack/attack-navigator#335]
Is there is any option other than sharing the json through github? Like i tried using drive but can't able to load..
So basically, how to share the json within an internal network?

**Comment by isaisabel** [comment]
Unfortunately there isn't really a good way to share layers over URL while also controlling access for those same layers. The ATT&CK Navigator cannot do any sort of authentication (such as that required to access google drive documents) when fetching layers so they have to be openly accessible to be used.

Theoretically if the layer file is accessible openly _within_ your organization's network but not outside of it (by allow-listing only your organization's IP addresses for example) you could get this behavior. But setting up such an environment would be outside of the purview of the ATT&CK Navigator. I would recommend talking to a sysadmin in your organization for help with that if you want to take that approach.

If you are working by yourself and simply want to more easily open layer files of your own, you can also specify default layers from your local filesystem in the config file if you set up your own Navigator instance. [See the README for more information](https://github.com/mitre-attack/attack-navigator#loading-default-layers-upon-initialization).
