### ISSUE TITLE
OOM after upgraded to v4.4.1

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-navigator#356]
Hi,

I met a critical error after updated to v4.4.1. I deployed navigator with Docker, and the error appears after i start the container.

![image](https://user-images.githubusercontent.com/8390209/133908800-cd9c1010-0baa-41e0-8601-54a43c325e6a.png)

then i try to checkout the code of version v4.3 and build the docker again, it seems verything is fine.

**Comment by jondricek** [comment]
This was fixed just now in this pull request: https://github.com/mitre-attack/attack-navigator/pull/395

It is now working on the develop branch
