### ISSUE TITLE
Autohide all techniques but those with a score

### ISSUE THREAD

**Issue by Pelios** [mitre-attack/attack-navigator#357]
I use Attack Navigator frequently to produce heat maps and i have not yet identified a quicker way to hide all techniques apart from those that have a score than just simply selecting the unscored techniques and disabling them. It would be useful if there was a button that could auto select all unscored techniques so that they could be disabled.

**Comment by isaisabel** [comment]
Hi @Pelios,

in the context menu (opened by right clicking a technique) you can use the "select unannotated" to select all techniques without a score, color, or comment. 

![image](https://user-images.githubusercontent.com/28868888/134691397-56ede407-e157-40bf-95cd-804d065141d6.png)

From there you can simply disable the selected techniques and then hide them as usual.

Does that meet your needs, or were you looking for a way even quicker than that?

**Comment by Pelios** [comment]
Hi @isaisabel 

That works perfectly! And i now feel very stupid for not noticing that before. Thank you very much!

**Comment by isaisabel** [comment]
Haha no worries, there are a ton of features in this application.

If you haven't seen it before, our USAGE document (https://github.com/mitre-attack/attack-navigator/blob/master/USAGE.md) (mirrored in the in-app help page) covers all the features as well as some tips. I think this particular use case is actually in a tip under [selecting techniques](https://github.com/mitre-attack/attack-navigator/blob/master/USAGE.md#selecting-techniques).
