### ISSUE TITLE
Generate and Publish Layers with ATT&CK Updates

### ISSUE THREAD

**Issue by jburns12** [mitre-attack/attack-navigator#37]
We should build a list of the set of layers that we think should be generated and published with each ATT&CK update and then create a process to generate these layers.

An example of this is creating layers that cover process information or command-line arguments for techniques those particular data sources apply to. A similar layer generation process could also be used to create layers based on mitigations.

**Comment by isaisabel** [comment]
Implemented in the [diff_stix](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/diff_stix.py) script on our attack-scripts repo. This script can output layers showing the changes in a given update.

See also https://github.com/mitre-attack/attack-website/issues/16 for more on automatic layer generation using `diff_stix`.
