### ISSUE TITLE
layout property in layer.json does not seem to work

### ISSUE THREAD

**Issue by thejjw** [mitre-attack/attack-navigator#381]
Hello,

I've cloned attack-navigator repository in current state at the time of writing and compiled using `ng build --prod --aot=false --build-optimizer=false`.
I'd like to note that the layout property in exported/crafted `layer.json` does not seem to be respected as of now(or I should learn to use it properly).
My exported layer.json has custom layout setting specified, just as I customized from the navigator itself:
```
{
	"name": "layer",
(...)
	"layout": {
		"layout": "side",
		"aggregateFunction": "average",
		"showID": true,
		"showName": false,
		"showAggregateScores": false,
		"countUnscored": false
	}
}
```
However, upon loading this layer from the navigator via either url parameter or `Open existing layer` > `Upload from local`, above layout configurations are not respected and instead default layout mode is shown.

Ideally in the future I want to automatically generate layer.json file from other source with layer configuration such as below:
```
{
	"name": "layer",
(...)
	"layout": {
		"layout": "side",
		"showID": true,
		"showName": false
	}
}
```

Could you offer me some insights to this issue?

Thanks.

**Comment by isaisabel** [comment]
Hi @thejjw,

This is definitely a bug -- long story short [when parsing the layout](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/viewmodels.service.ts#L1819-L1844) the app checks if the fields exist. This is currently written incorrectly, it should be `if ("showID" in rep)`, not `if (rep.showID)` (for example) -- in the latter implementation `rep.showID` (being a boolean) will not get parsed if it is false. 

I'll be releasing a patch with a fix for this this later today.
