### ISSUE TITLE
Technique background colors are broken (e.toHex8String is not a function)

### ISSUE THREAD

**Issue by cr-simmons** [mitre-attack/attack-navigator#386]
Using any layer configuration with a "color" attribute defined in a technique, or attempting to manually color a technique from the UI leads to an error.

![Screen Shot 2021-11-12 at 17 59 39](https://user-images.githubusercontent.com/77048809/141440133-38d9c35f-5d40-444b-b4ee-d2cf47b99c33.png)

**Comment by cr-simmons** [comment]
The issue appears to have been caused here
https://github.com/mitre-attack/attack-navigator/commit/596157652db2391d5fd311e908abaa8a88e35e7d#diff-e49d1d934cc9d96bce820fb261164a66e14c3c90fa2364ff83b6d12201992182R78
and the code should instead be
```
let cell_color = tinycolor(color).toHex8String()
```

**Comment by isaisabel** [comment]
Thanks for pointing this out. I'll be patching this later today.
