### ISSUE TITLE
Non covered techniques as full black when opening existing layer

### ISSUE THREAD

**Issue by francolmenar** [mitre-attack/attack-navigator#388]
This bug I think is present since the end of last week, mainly because I just found it out this morning and I have been working with the tool the whole last week.

The issue is that when an existing layer is open the non covered techniques are colored with black, see below the image. However, when I export it to svg the non covered techniques goes back to the normal color.

![Screenshot 2021-11-15 at 11 55 35](https://user-images.githubusercontent.com/26555472/141770595-9bab34df-510c-4bfa-80ba-623b9465d5c9.png)

It would be nice if this could be fixed because even though it is still possible to export it as svg correctly, it is a bit painful to use the tool right now because you have to hover the techniques to just see their name.

**Comment by isaisabel** [comment]
Hi @francolmenar,

Can you upload a layer file (or example layer file) which exhibits this behavior? We made some adjustments to the cell coloring code in v4.5.3 on Friday which is likely the culprit. We'll try to get a patch out shortly fixing this.

**Comment by isaisabel** [comment]
Do you have aggregate scores enabled? I can partially replicate this when enabling aggregate scores on a layer. Specifically the cell color but not the cell text color turns black when enabling aggregate scores.

**Comment by isaisabel** [comment]
Fixed in v4.5.4. Should be up on the live instance in a few minutes.

**Comment by francolmenar** [comment]
Thanks for your quick help!
