### ISSUE TITLE
Feature request: Theme customization

### ISSUE THREAD

**Issue by zacheller** [mitre-attack/attack-navigator#393]
Hi there!

I use Navigator with the dark theme, and the colors for covered vs uncovered techniques are fairly close together. The light theme makes those distinctions very clear, and I'd like to have the same in dark mode for presenting. Is there a way to implement customization of the background and text color by covered and uncovered techniques?

**Comment by iguannalin** [comment]
Hi @zacheller ,
I'm not familiar with covered techniques. Do you have a screenshot of the covered vs uncovered techniques you can share, possibly?

**Comment by zacheller** [comment]
Covered as in the techniques that are specified in the "techniques" field of the JSON when a layer is exported. I can change the background color of all those technique manually in the tool or by find-and-replace inside the JSON. However, I cannot easily change the background color of the techniques that I have not scored or given metadata, etc.

If I cover #1F262E:
```json
{
	"name": "example-layer",
	"versions": {
		"attack": "10",
		"navigator": "4.5.4",
		"layer": "4.2"
	},
	"domain": "enterprise-attack",
	"description": "",
	"filters": {
		"platforms": [
			"Linux",
			"macOS",
			"Windows",
			"Azure AD",
			"Office 365",
			"SaaS",
			"IaaS",
			"Google Workspace",
			"PRE",
			"Network",
			"Containers"
		]
	},
	"sorting": 0,
	"layout": {
		"layout": "side",
		"aggregateFunction": "average",
		"showID": false,
		"showName": true,
		"showAggregateScores": false,
		"countUnscored": false
	},
	"hideDisabled": false,
	"techniques": [
		{
			"techniqueID": "T1176",
			"tactic": "persistence",
			"color": "#1F262E",
			"comment": "",
			"enabled": true,
			"metadata": [],
			"showSubtechniques": false
		}
	],
	"gradient": {
		"colors": [
			"#ff6666ff",
			"#ffe766ff",
			"#8ec843ff"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": true,
	"selectSubtechniquesWithParent": false
}
```
![light](https://user-images.githubusercontent.com/18650767/144976934-4fa2ea1b-e8ef-4227-8601-f78fabedd642.png)
![dark](https://user-images.githubusercontent.com/18650767/144976940-d8c9a4b6-6d57-4671-ab76-ebf22000c55e.png)
