### ISSUE TITLE
Feature request: User-defined website link

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-navigator#396]
Hi,

I deployed a attack-navigator instance locally and add some new items(techniques and groups, etc) related to my organization. for the new items, when I click `view xxx` it will jump to online attck-website, which obviously don't contains my items. the page will showns 404.

Is there any easy to change the linke under `view` action. I have a local attck-website, and i want let navigtor jump to my owne attack-website, so that it will show the items defined by my organization.

**Comment by clemiller** [comment]
Hi @dickens88,

You can create your own user-defined website links via the custom context menu field in the configuration file. This will add new options underneath the existing `view tactic/technique` options in the context menu (example shown below). Your defined custom context URL would look something like `http://www.someurl.com/{{technique_attackID}}}` and would point to your local ATT&CK website instance. The instructions on how to do this can be found [here](https://github.com/mitre-attack/attack-navigator#adding-custom-context-menu-options).

![image](https://user-images.githubusercontent.com/48832936/148084385-5563ffe6-50bf-4d57-a7bb-77dba31a292d.png)

**Comment by dickens88** [comment]
Hi @clemiller,

Thank you so much for your reply. 

The method mentioned is working, but that method can only customize the url option in the right-click menu, and the links contained in other entities in the sidebar cannot be customized. please correct me if i was wrong. thank you again.

![image](https://user-images.githubusercontent.com/8390209/148145811-88399cfc-b6a1-4414-8bc5-f70122d7d9cd.png)

**Comment by clemiller** [comment]
That's correct. The links in the sidebar are not currently customizable.
