### ISSUE TITLE
Can't sync Group and DataSource oject from ATT&CK Workbench

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-navigator#397]
Hi,

I'm working on  navigator v4.5.4, and trying to get data from ATT&CK Workbench v1.1.0.

I have configured navigator integrate workbench address, accroding to [this guide](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md). 

I created user-defined technique, mitigation, group, software, datasource one for each in workbench. after a while, i tried to find them in Navigator(The Navigator should sync all the new items i created in workbench as i understand). 

But `threat group` and `datasource` can not be found there (technique, mitigation, software are synchronized correctly)

I suppose maybe some errors happened when handling group and datasource.

**Comment by clemiller** [comment]
Hi @dickens88,

There appears to be a small bug when handling the importing of Group objects from the Workbench. I have opened a bug report for this, which can be tracked [here](https://github.com/mitre-attack/attack-navigator/issues/399).

For data sources to appear in the Navigator, they must have at least one data component and at least one of those data components must have a relationship with a technique in the Enterprise domain.

**Comment by dickens88** [comment]
Hi @clemiller , 

Got it, thank you for the information.
