### ISSUE TITLE
Docker issues when installing for private production instance

### ISSUE THREAD

**Issue by Ach13v3-M0n7** [mitre-attack/attack-navigator#401]
I received multiple errors when attempting to build Navigator in my environment.

Steps to gather requirements:
`apt install nodejs`
`npm install -g @angular/cli`
`git clone https://github.com/mitre-attack/attack-navigator`

When I perform the `docker build -t customname .`, this is the output I recieve:

Sending build context to Docker daemon  32.72MB
Step 1/11 : FROM node:16
16: Pulling from library/node
9b99af5931b3: Pull complete
b6013b3e77fe: Pull complete
bbced17b6899: Pull complete
8b609dabefa8: Pull complete
50544bfef33d: Pull complete
fea3f8b8e075: Pull complete
c81dbcaf60d9: Pull complete
7b0e069b3bda: Pull complete
29ac9271f536: Pull complete
Digest: sha256:32605ead97ed57bd39a8a7b0e919240e1a3218974dfc6965e61b54a801753131
Status: Downloaded newer image for node:16
 ---> 8381a2328ac2
Step 2/11 : WORKDIR /src
 ---> Running in 62d707825d8a
Removing intermediate container 62d707825d8a
 ---> 7034cc6c2572
Step 3/11 : COPY nav-app/ /src/nav-app/
 ---> 0a0266311c49
Step 4/11 : COPY layers/*.md /src/layers/
 ---> dea1db6b8faf
Step 5/11 : COPY *.md /src/
 ---> 015a5250763b
Step 6/11 : WORKDIR /src/nav-app
 ---> Running in d7b56ef2e0de
Removing intermediate container d7b56ef2e0de
 ---> e6c9dc6e7c6d
Step 7/11 : RUN chown -R node:node ./
 ---> Running in b9175712aac1
Removing intermediate container b9175712aac1
 ---> 4ee3e87643e1
Step 8/11 : RUN npm install --unsafe-perm
 ---> Running in 0b7075f63284
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'karma-cli@1.0.1',
npm WARN EBADENGINE   required: { node: '0.10 || 0.12 || 4 || 5 || 6' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the
URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain
circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less
dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less
dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when
used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1
(https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when
used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1
(https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when
used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1
(https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when
used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1
(https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated @angular/http@7.2.16: Package no longer supported. Use @angular/common instead, see
https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see
https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the
number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x
even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

###########
BREAK
###########

The build process continues until it completes, but, in my ignorance/lack of experience with angular/node, I'm not sure if I did something wrong. The guide does not specify which versions of Node/Angular I should have installed.

**Comment by clemiller** [comment]
Hi @Ach13v3-M0n7,

The specific versions of Node/Angular needed are handled by both the Dockerfile and the application package files, and are not something you need to install yourself.

The output from the build process are warnings caused by sub-dependencies of packages we use which have been deprecated. These deprecated dependencies would need to be updated by the package maintainers. These are not issues that impact the build process and can be ignored.

**Comment by Ach13v3-M0n7** [comment]
Thanks for the clarification. That was my, albeit, uncertain understanding.
