### ISSUE TITLE
can add Detection and Mitigations ？

### ISSUE THREAD

**Issue by ming54864** [mitre-attack/attack-navigator#410]
we need to add score in Detection and Mitigations,can add column end of sub Sub-techniques？

**Comment by ming54864** [comment]
thinks.

i would like to add scores/comment to Detection (or Mitigations), for example：
<img width="866" alt="image" src="https://user-images.githubusercontent.com/7892320/155291981-bbbfbc9f-39c6-4f1d-a9e5-0b207829bfe1.png">

**Comment by clemiller** [comment]
Adding new matrix cells for other ATT&CK objects is outside of the scope of the Navigator. The Navigator is designed to provide the navigation and annotation of ATT&CK Techniques. Mitigations can have relationships with multiple techniques and/or sub-techniques which would make the UI difficult to navigate and extend beyond the intended functionality. 

I recommend using [metadata](https://github.com/mitre-attack/attack-navigator/blob/master/USAGE.md#adding-metadata-to-techniques) to add detection/mitigation scores to techniques/sub-techniques directly, using this technique control interface:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/48832936/155334139-35a3c6ce-d3b7-44c4-90ae-a13cbe5a145b.png">

Metadata can be assigned unique names and values, so you could provide scores/comments to Mitigations in this way:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/48832936/155333114-bb2ef47c-f8a4-4df5-a4d7-d87282ae665a.png">

**Comment by ming54864** [comment]
thanks
