### ISSUE TITLE
Auto-save Feature

### ISSUE THREAD

**Issue by jburns12** [mitre-attack/attack-navigator#42]
A user has mentioned that it would be nice if layer controls could have an option to enable "auto-save" so you don't lose your work.

**Comment by isaisabel** [comment]
Autosave has been discussed in the past. The difficulties with this feature is how autosave would be implemented. 

1. Opening a "save locally" prompt at frequent intervals would be obtrusive to the user experience.
2. Cookies has a maximum storage size; putting layers into cookies runs into scalability issues (if I remember my calculations correctly we could only fit 5-6 layers into cookies assuming every technique is annotated). Clearing cookies would delete layers, and if users don't make local backups they could lose work.

Some possible solutions:

1. The JS [indexed database API](https://www.wikiwand.com/en/Indexed_Database_API) shows promise as a way to get around the storage size limits. However, compatibility and reliability needs to be assessed.
2. An optional local database could be developed, and the configuration of the navigator could be modified to allow connection to a database running on the local machine. Changes would be automatically saved there for future editing, and the "open existing layer" panel on the Navigator could be modified to show a list of layers in the database. However, this is a departure from the current design of the navigator as a browser-only application.
