### ISSUE TITLE
API for MITRE Navigator??

### ISSUE THREAD

**Issue by call-me-tj** [mitre-attack/attack-navigator#421]
I wanna know if there is an API  that I can use to interact with MITRE Navigator.

**Comment by clemiller** [comment]
Hi @call-me-tj,

ATT&CK Navigator is a client-side only application and does not have an API or a back-end. However, we do have additional tools which can replicate some of the ATT&CK Navigator features:
- [mitreattack-python](https://github.com/mitre-attack/mitreattack-python): contains a collection of utilities to work with Navigator layers. This library can be used to generate, manipulate, and export Layer files in a similar way the Navigator does. Here's a link to the [navlayers module](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/README.md) within mitreattack-python where you can read more about how it can be used.
- [attack-scripts](https://github.com/mitre-attack/attack-scripts): contains some standalone scripts which can generate layer files. The [diff_stix script](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/diff_stix.py) can be used to diff two versions of the ATT&CK dataset and create a layer representing the changes. There are also various example layer generators in the [sample scripts](https://github.com/mitre-attack/attack-scripts/tree/master/scripts/layers/samples) directory.
