### ISSUE TITLE
Double ICS platforms

### ISSUE THREAD

**Issue by marcusbakker** [mitre-attack/attack-navigator#430]
I believe something is going wrong in the ICS platforms of the Navigator. There are double entries because some have a space in front of the name. E.g. "Input/Output Server"

![image](https://user-images.githubusercontent.com/40516252/166107050-ee117a5e-0bea-4e39-b2e2-abd76c67442e.png)

**Comment by clemiller** [comment]
Hi @marcusbakker,

Thanks for opening an issue for this bug! This is a known issue with the ICS STIX data (some platforms have leading whitespaces) and we are working on cleaning up the data. In the meantime, a fix for the duplication in the Navigator has been staged on `develop` and will be included in the next Navigator release.
