### ISSUE TITLE
Fails to load any layers with a score or color defined on a technique.

### ISSUE THREAD

**Issue by cr-simmons** [mitre-attack/attack-navigator#452]
Produces "ReferenceError: tinycolor is not defined"

![Screen Shot 2022-05-13 at 12 32 15](https://user-images.githubusercontent.com/77048809/168206034-893740a7-3fcc-44c7-9309-c3b7784f64e0.png)

**Comment by clemiller** [comment]
Hi @cr-simmons 

Thank you for opening a bug report and providing a reference to the error! We have pushed a new release with the fixes for this issue, and it will be live on the Navigator shortly.
