### ISSUE TITLE
Show/hide disables is not working proparly

### ISSUE THREAD

**Issue by rsagy** [mitre-attack/attack-navigator#466]
Hi
When I tried to disable all Mitre technique/sub techniques, its show them also the "enabled": false was set.
Attached 2 examples: 
1. The first one disables all items, so it should show no techniques, but it still shows some techniques
2. The second one is a bit more advance: it should show some techniques/sub techniques with colors and disable most of the other techniques
 Please advice
[data.zip](https://github.com/mitre-attack/attack-navigator/files/8708739/data.zip)

**Comment by clemiller** [comment]
Hi @rsagy,

Thank you for opening this issue! This was a bug in how the "enabledness" of sub-techniques was being determined, which disregarded the filters in place. A fix for this has been staged on `develop` and will be included in the next Navigator release.

**Comment by rsagy** [comment]
Thanks a lot for the fast response

Have a nice day
Ravid
