### ISSUE TITLE
Feature Request: Allow `view technique` of custom techniques

### ISSUE THREAD

**Issue by mticmtic** [mitre-attack/attack-navigator#483]
Currently, when right clicking on a technique --> view technique, it takes you to the attack.mitre.org. When trying to do that with a custom technique, you get a 404 error. Request the ability to point this a local ATT&CK website.

**Comment by clemiller** [comment]
Hi @mticmtic!

You can create your own user-defined website links via the custom context menu field in the configuration file. Alternatively, with the implementation of [#321](https://github.com/mitre-attack/attack-navigator/issues/321), this can also be done through the Navigator's "link" interface.

![image](https://user-images.githubusercontent.com/48832936/189914377-a7ec06e4-d683-440c-a64b-23d6f96bb29d.png)

This will add new options underneath the existing view tactic/technique options in the context menu (example shown below). Your defined custom context URL would look something like http://www.someurl.com/{{technique_attackID}}} and would point to your local ATT&CK website instance. More detailed instructions on how to do this can be found [here](https://github.com/mitre-attack/attack-navigator#adding-custom-context-menu-options).

![image](https://user-images.githubusercontent.com/48832936/189914102-5e41f497-c48a-4c3b-a34d-5935752c863a.png)

**Comment by mticmtic** [comment]
This is awesome! Great feature. Thank you
