### ISSUE TITLE
Running Error - Step 8/11 : RUN npm install --unsafe-perm  

### ISSUE THREAD

**Issue by M0dred** [mitre-attack/attack-navigator#497]
Step 8/11 : RUN npm install --unsafe-perm
 ---> Running in ac292f6fe2fb

npm notice 
npm notice New minor version of npm available! 8.15.0 -> 8.19.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.0>
npm notice Run `npm install -g npm@8.19.0` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular-devkit/build-angular@0.1100.7
npm ERR! Found: karma@5.0.9
npm ERR! node_modules/karma
npm ERR!   dev karma@"~5.0.0" from the root project
npm ERR!   peer karma@"*" from karma-jasmine@4.0.2
npm ERR!   node_modules/karma-jasmine
npm ERR!     dev karma-jasmine@"~4.0.0" from the root project
npm ERR!     peer karma-jasmine@">=1.1" from karma-jasmine-html-reporter@1.7.0
npm ERR!     node_modules/karma-jasmine-html-reporter
npm ERR!       dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!   1 more (karma-jasmine-html-reporter)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional karma@"~5.1.0" from @angular-devkit/build-angular@0.1100.7
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1100.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: karma@5.1.1
npm ERR! node_modules/karma
npm ERR!   peerOptional karma@"~5.1.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1100.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-01T10_46_17_505Z-debug-0.log

The command '/bin/sh -c npm install --unsafe-perm' returned a non-zero code: 1

**Comment by jinxka** [comment]
Hello,

I have the same issue, any update on this?

**Comment by rascal999** [comment]
Can confirm this issue while trying to use docker.

**Comment by jondricek** [comment]
@seansica will you please look into this and investigate what is going awry with the Docker build?

**Comment by rascal999** [comment]
Using node:14 instead of 16 fixed the docker build.

**Comment by jondricek** [comment]
I just accepted @seansica's pull request which addresses the issue a different way - by tacking on `--legacy-peer-deps` to the `npm install` command. This fix is in the develop branch for now, so it will be included in the next release. I'll keep this issue open until then.
