### ISSUE TITLE
Change default branch on GitHub

### ISSUE THREAD

**Issue by sergiuser1** [mitre-attack/attack-navigator#504]
Hi, it looks like the default branch now is "master", whereas the most up-to-date and active branch is "develop". Can you change the default branch to "develop"? Thanks.

**Comment by jondricek** [comment]
I realize you closed the issue, but I just wanted to step in and clarify that the develop branch may have more active development, but that doesn't reflect what is released onto the public site.

The master branch is what you should see over at https://mitre-attack.github.io/attack-navigator.

Hope that helps clear up any confusion about our development practices!
