### ISSUE TITLE
Where is The layer upgrade interface ?

### ISSUE THREAD

**Issue by kripskroll** [mitre-attack/attack-navigator#524]
Hi all,

I sincerely apologise for this stupid question, but I spent lot of time to find the layer upgrade interface without success.
I can't see it on the default navigator at https://mitre-attack.github.io/

Is there a dedicated URL for it ?

Here is my default view of it :

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/676114/205344264-91ef719c-eca0-45fb-b3b7-a2943fcb81f7.png">

Thanks in advance for your kind help

**Comment by kripskroll** [comment]
Just open the file in the Load Existing Layer and it will be prompted if older version detected.
Sorry for the noise

**Comment by clemiller** [comment]
Hi @kripskroll. I saw you closed this, but figured I'd provide an answer anyway just in case someone else has the same question.

The layer upgrade interface will automatically open when you upload an existing layer into the Navigator, if the layer was created with a previous version of ATT&CK. A pop-up will appear asking if you want to upgrade the layer; if you click yes, the interface will open in a sidebar on the right. You can read more about the process of upgrading a layer in the [USAGE document](https://github.com/mitre-attack/attack-navigator/blob/master/USAGE.md#upgrading-a-layer-to-the-current-version). Hope this helps!

<img width="500" alt="image" src="https://user-images.githubusercontent.com/48832936/205345649-13857bb5-7570-4462-b7b3-9eca50f69e02.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/48832936/205345925-fcc255ca-aa8c-4904-8e00-b266aed8797f.png">
