### ISSUE TITLE
Update Node.js 16 to 18

### ISSUE THREAD

**Issue by Kuermel** [mitre-attack/attack-navigator#540]
https://github.com/nodejs/Release

Node.js 16 has now reached maintenance mode and will reach end-of-life on 2023-09-11. 
The new LTS version is Node.js 18. 

The Docker file should be adapted accordingly.

**Comment by erinehall** [comment]
Hi @Kuermel 

Thank you for bringing this to our attention! The changes have been staged in develop and will be included in the next Navigator release.
