### ISSUE TITLE
Is there a way to programmatically download from Navigator?

### ISSUE THREAD

**Issue by metalshanked** [mitre-attack/attack-navigator#549]
Hi,

Is there a way to programmatically download JSON from Navigator?
Since currently the download is via an internal JS call. Is there a URL/Parameter option to call to download the JSON?

![image](https://user-images.githubusercontent.com/57646596/232174492-c7d40c71-c039-432b-a504-2cc317e6bddf.png)

**Comment by clemiller** [comment]
Hi @metalshanked,

ATT&CK Navigator is a client-side only application and does not have an API available to download a layer programmatically. However, there are some additional tools available in the [mitreattack-python](https://github.com/mitre-attack/mitreattack-python) library that can replicate some of the features of Navigator programmatically. Our [navlayers](https://github.com/mitre-attack/mitreattack-python/tree/master/mitreattack/navlayers) module has functionality to generate, manipulate, and export Layer files in a similar way Navigator can. I'd recommend checking it out to see if this library may be able to help you accomplish your goal.
