### ISSUE TITLE
Export to excel with comments

### ISSUE THREAD

**Issue by sfakiana** [mitre-attack/attack-navigator#55]
Current capability is to export to excel. However, comments are lost when this feature is used. It would be great to have the capability to export to Excel and also keep the comments in Excel.

**Comment by jburns12** [comment]
Thanks for bringing this to our attention @sfakiana and for recommending this feature. It's unclear when our developers would have the bandwidth to implement this, so if you or anyone else wants to tackle this feel free to submit a pull request!

**Comment by isaisabel** [comment]
This is now possible with the newest version of ExcelJS using [cell comments](https://github.com/exceljs/exceljs#cell-comments).

**Comment by isaisabel** [comment]
Feature added in [feature/excel-comments](https://github.com/mitre-attack/attack-navigator/tree/feature/excel-comments) and merged into develop.
