### ISSUE TITLE
Scroll down in subwindows doesn't seem to work

### ISSUE THREAD

**Issue by 111andre111** [mitre-attack/attack-navigator#559]
In Attack Navigator if there is embedded some link with multiple subitems I can't see any possibility to scroll down the rules subwindow.
I supposed this might be a bug.

I don't know how to better describe that so I offer the link I use and a screenshot:
https://ela.st/protections-artifacts-navigator

<img width="280" alt="Screenshot 2023-06-15 at 12 48 53" src="https://github.com/mitre-attack/attack-navigator/assets/48132449/18aef720-be99-4c79-9daa-3c7ab0e8abc1">

**Comment by clemiller** [comment]
Hi @111andre111,

Thanks for reaching out and providing a link to your layer! I believe this is the same issue that was reported in #320, where it's difficult to scroll in the the box that pops up next to a technique when your mouse hovers over it. For this reason, there's an option in the context menu (accessed by right-clicking on a technique) to pin the tooltip. The tooltip will remain open until you click elsewhere and you'll be able to scroll through the items:

![image](https://github.com/mitre-attack/attack-navigator/assets/48832936/bbadcd66-bd14-4a91-b081-e18884591aa0)

**Comment by 111andre111** [comment]
Cool. Very nice. That did the trick. Very much thank you. Wasn't aware of that feature.
