### ISSUE TITLE
Add "Expand Annotated Sub-Techniques" to layer file format

### ISSUE THREAD

**Issue by initstring** [mitre-attack/attack-navigator#560]
Inside the ATT&CK Navigator UI, there is an option to "expand annotated sub-techniques".

<img width="836" alt="image" src="https://github.com/mitre-attack/attack-navigator/assets/26131150/6d4f910c-3ad4-43ed-aeee-cb94933cc0e9">

It would be nice if we could define this inside a layer file, to ensure this view loads on default.

Perhaps a good spot for this would be in the `layout` section, like this:

```
	"layout": {
		"layout": "flat",
		"expandAnnotatedSubtechniques": true
	},
```

We use Navigator inside a CI pipeline, which automatically generates layer files and builds a static website for us to compare individual and combined red team operation output. For us, it is a dashboard we can visit to view our progress over time. Having this view defined automatically would ensure everyone gets a consistent experience, and having these expanded by default ensures people's eyes are drawn to the specific techniques we have annotated.

Thank you for all your hard work on a great tool!

**Comment by clemiller** [comment]
Changes for this issue have been staged on `develop` and will be included in the next release.

An optional property called `expandedSubtechniques` will be added to the `layout` section in the Layer file and can be set to `all`, `annotated`, or `none`. This will expand all subtechniques, expand only annotated sub-techniques, or collapse all sub-techniques respectively. Thank you for your suggestion!

**Comment by initstring** [comment]
Thanks so much for your work on this, @clemiller!

I know this issue is closed, but I was hoping to also draw attention to [this other issue](https://github.com/mitre-attack/attack-navigator/issues/123#issuecomment-1596274133), as it is related. Perhaps it could be addressed in the same way?

Thanks again for your hard work on this great tool.

**Comment by clemiller** [comment]
Hi @initstring, I have added #123 to our next milestone and will have our team start looking into it following the upcoming release.
