### ISSUE TITLE
Color feature not working. 

### ISSUE THREAD

**Issue by savanahbugarin** [mitre-attack/attack-navigator#563]
Been using MITRE Navigator on high side and recently the color feature has not been working. 
![image](https://github.com/mitre-attack/attack-navigator/assets/139368657/f32f4f86-beba-4ed8-9c5f-b8ef2c9db6c7)
We have had both the scoring and color setup for the past year that we've been updating this layer and it's been functioning fine but recently the colors have not been showing up. Currently tried the layer on both v4.8.2 and v4.8.1 but still no luck. Any help would be greatly appreciated.

**Comment by ezaspy** [comment]
I am experiencing the same issue. This is my config.json
[config.json.txt](https://github.com/mitre-attack/attack-navigator/files/12134836/config.json.txt)
And this is the screenshots of it working online, but not on local instance - note the numbers in the corner of the techniques selected - for some reason the colour doesn't show
<img width="1190" alt="local" src="https://github.com/mitre-attack/attack-navigator/assets/42219366/6e2e88d4-7075-4016-8d93-9f9c2a16a0dd">
<img width="1227" alt="github" src="https://github.com/mitre-attack/attack-navigator/assets/42219366/bf2f7f19-2380-40a6-8f62-e1d6aa634ee7">
I have uploaded my layer.json file too for you to replicate
[layer.json.txt](https://github.com/mitre-attack/attack-navigator/files/12134860/layer.json.txt)

**Comment by clemiller** [comment]
@ezaspy, thanks for hopping over here & sharing your files!

There were new configuration options added in v4.8.1, which appear not have been pulled into the config file. These are coloring effect options that can be enabled/disabled (issue #371), and are disabled by default if missing from the configuration. Please pull in the latest changes to the config, check that the three lines below appear under `technique_controls`, and rebuild the Navigator. This should re-enable the coloring effects on your local instance.

```json
{"name": "background_color", "enabled": true, "description": "Disable to remove the background color effect on manually assigned colors."},
{"name": "non_aggregate_score_color", "enabled": true, "description": "Disable to remove the color effect on non-aggregate scores."},
{"name": "aggregate_score_color", "enabled": true, "description": "Disable to remove the color effect on aggregate scores."},
```

**Comment by ezaspy** [comment]
That worked for me! Thank you @clemiller

**Comment by clemiller** [comment]
Closing as resolved. @savanahbugarin, please feel free to re-open this issue if the above fix does not work for you!
