### ISSUE TITLE
ERROR parsing layer from assets/casetest.json, check the javascript console for more information.

### ISSUE THREAD

**Issue by ezaspy** [mitre-attack/attack-navigator#565]
Hi,

I am really struggling to understand why my layer file casetest.json is not loading into attack-navigator.
My use case is to load a default layer (example casetest.json) upon visiting localhost:4200, but i get the following error:
`ERROR parsing layer from assets/casetest.json, check the javascript console for more information.`
Please find attached my files for review
Thanks
[casetest.json.txt](https://github.com/mitre-attack/attack-navigator/files/12122960/casetest.json.txt)
[config.json.txt](https://github.com/mitre-attack/attack-navigator/files/12122961/config.json.txt)
[enterprise-attack.json](https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json)
<img width="1363" alt="Screenshot2" src="https://github.com/mitre-attack/attack-navigator/assets/42219366/7d5ec77b-9574-43e4-9ece-ae6f56bce0d4">

<img width="1363" alt="Screenshot1" src="https://github.com/mitre-attack/attack-navigator/assets/42219366/c4e8b6ee-1886-451e-9d8f-a6c43d4b06e6">

**Comment by clemiller** [comment]
Hi @ezaspy,

There appear to be some missing fields in your `config.json` file and what appears to be a small discrepancy in the ATT&CK versions between the config and `casetest.json`.
1. The Enterprise domain config is missing both the `version` and the `identifier` fields, which are needed to properly load the correct domain/version into the Navigator as defined in your layer:
```json
"versions": [
    {
        "name": "ATT&CK v9",
        "version": "9", <----
        "domains": [
            "name": "Enterprise",
            "identifier": "enterprise-attack", <----
            "data": [ "assets/enterprise-attack.json" ]
        ]
    }
]
```

2. The attack version listed in `casetest.json` is `"attack": "13"`, however it _appears_ your config only defines the data source for ATT&CK version 9 (this is my assumption based on the name defined in your config file). When loading your layer file, the Navigator will match your layer's attack version & domain to the `version` and `identifier` fields defined in the config file. In its current state, there will not be a match and the layer will fail to load. One or the other would need to be updated in this case, depending on the desired version.

I hope this helps!

**Comment by ezaspy** [comment]
Thank you @clemiller I will test and confirm shortly. Curious - if I wanted the page to reflect the latest version of ATT&CK so I just update the config.json file?

**Comment by clemiller** [comment]
Yes, if you'd like to build your layer on ATT&CK v13, you can update the `versions` field in your config file to define where the v13 data is located. Since the `enterprise-attack.json` file you supplied points to the latest version, you only need to update the name & version:

```json
"versions": [
    {
        "name": "ATT&CK v13",
        "version": "13",
        "domains": [
            "name": "Enterprise",
            "identifier": "enterprise-attack",
            "data": [ "assets/enterprise-attack.json" ]
        ]
    }
]
```

**Comment by ezaspy** [comment]
I'm getting an error with the above code
Should it be this:
```
    "versions": [
        {
            "name": "ATT&CK v13",
            "version": "13",
            "domains": [
                {
                    "name": "Enterprise",
                    "identifier": "enterprise-attack",
                    "data": [
                        "assets/enterprise-attack.json"
                    ]
                }
            ]
        }
    ],
```

**Comment by ezaspy** [comment]
Your solution (with [this code](https://github.com/mitre-attack/attack-navigator/issues/565#issuecomment-1646088387)) does work - thank you but I now have another issue - duplicate of #563
