### ISSUE TITLE
UI Improvements to better handle many open tabs

### ISSUE THREAD

**Issue by initstring** [mitre-attack/attack-navigator#580]
We deploy Navigator automatically, and configure it to load layer files from previous Red Team operations. When the web application opens with many tabs, it becomes difficult to navigate the interface.

The number of tabs cannot be seen in a reasonable-sized browser window, and there is no specific interface to scroll horizontally between the tabs.

![image](https://github.com/mitre-attack/attack-navigator/assets/26131150/d010b9f4-f9b5-43c9-8d3e-6580571fa7bf)

Two horizontal scroll bars appear at the bottom of the browser window, but scrolling the bottom-most bar breaks the UI.

![image](https://github.com/mitre-attack/attack-navigator/assets/26131150/1e2201a8-c18e-4322-ae68-292776d48551)

Expanding the browser window itself works, but there is a limit here depending on the screen size the person is working on.

It would be nice to have some UI improvement to deal with many open tabs, possibly something like:
- Shrinking size of tabs
- Allowing horizontal scroll interface at the tab level itself

I am using Safari and the most recent Navigator release.

Thanks for your hard work!

**Comment by clemiller** [comment]
Changes for this issue have been staged on `develop` and will be included in the next release. This will add the ability to scroll horizontally through the open tabs. Thank you for your suggestion!
