### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by kcohne** [mitre-attack/attack-navigator#601]
Trying to build docker to run locally and keep getting this error. This is on Ubuntu 20.04.1

![image](https://github.com/mitre-attack/attack-navigator/assets/30534531/6a332dcf-7b7a-4f36-89b4-7925818e2ce3)

**Comment by clemiller** [comment]
Hi @kcohne,

Thanks for reporting this issue. A fix for this issue has been staged on `develop` and will be included in the next release (#598).
