### ISSUE TITLE
Coundn't find a way to make a statistic of the technique score of all the apt groups

### ISSUE THREAD

**Issue by ShadowZzj** [mitre-attack/attack-navigator#609]
In my case, I want to make a statistic of the technique used by apt groups. For exmaple, If APT1 and APT2 both use technique1, then the score of technique1 should be 1 + 1. I want the calculation goes like this and finally I want to make a full view  and weight of all the techniques. Could it be done?

I find a way that is too exhausting. For every APT group, I need to establish a layer. Then I use Create layer From Other Layers to set the score expression to a + b + c +d ......

**Comment by clemiller** [comment]
Hi @ShadowZzj,

The functionality you're looking for sounds somewhat similar to issue #150 (identifying the number groups that use a particular technique) and I would iterate most of what isaisabel mentioned in the comments. That said, there are a couple of ways this could be achieved without manually creating each layer via Navigator:

1. It may be easiest to write a script that parses the STIX data from the [MITRE/CTI repo](https://github.com/mitre/cti) and generate a layer file that shows usage by APT groups. The [mitreattack-python library](https://github.com/mitre-attack/mitreattack-python) has some useful [scripts for generating Navigator layers](https://github.com/mitre-attack/mitreattack-python/tree/master/mitreattack/navlayers). There is a lot of various functionality in there, but based on what you're looking for, I'll specifically point out [usage_generator.py](https://github.com/mitre-attack/mitreattack-python/tree/master/mitreattack/navlayers#usage_generatorpy), [sum_generator.py](https://github.com/mitre-attack/mitreattack-python/tree/master/mitreattack/navlayers#sum_generatorpy), or [layergenerator_cli.py](https://github.com/mitre-attack/mitreattack-python/tree/master/mitreattack/navlayers#layergenerator_clipy). Each of these scripts can generate a layer based on a specified ATT&CK object or ATT&CK object type. These could be used in conjunction with a custom script that adds the scores together on a per technique basis. Writing a script to generate the layer would also provide greater flexibility in what information it contains (e.g. metadata could be included on each technique to indicate which specific APT groups use it).
     - We also have some example Python scripts in the [attack-scripts repo](https://github.com/mitre-attack/attack-scripts/tree/feature/%2321-layer-sample-scripts/scripts/layers/samples) that demonstrate how layers can be generated from the STIX data. This repository has been archived, but they may be useful as a reference.

2. Another option would be to download the usage layers for each individual APT group from the ATT&CK Website- each technique used by a specific group is given a score of 1. The layers could then be added together in the Navigator's "create layers from other layers" interface.

    <img width="1630" alt="Screenshot 2024-01-26 at 9 58 38 AM" src="https://github.com/mitre-attack/attack-navigator/assets/48832936/0c122bc3-cf6b-4baf-b27c-ec7623a26f5f">

I hope this is helpful. Please let me know if you have any other questions!

**Comment by ShadowZzj** [comment]
Think it would be nice to have a better way to achieve that. I have used an hour to learn the navigator. It is fine. However, to achieve my little custom goal (which is intuitive), I need to learn anothor more hours (5 hours maybe?). But still thanks!
