### ISSUE TITLE
Bug Fix: Cannot create or load Navigator Layers on ATT&CK v10 or earlier 

### ISSUE THREAD

**Issue by mikecarenzo** [mitre-attack/attack-navigator#620]
### What Happened:
It seems the recent update to ATT&CK Navigator (v4.9.2) has broken the Navigator's ability to create and load Navigator Layers on ATT&CK v10 and earlier. Attempting to create or load a layer on these versions of ATT&CK results in the following error:

![image](https://github.com/mitre-attack/attack-navigator/assets/79934822/ac6b3d2b-9d1d-4ebf-bb9e-a86853e04931)

### To Reproduce:
1. Open [ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/)
2. Click "Create New Layer"
3. Click "More Options"
4. Under "Select a version" choose any ATT&CK version between v4 and v10
5. Under "Select a domain" choose "Enterprise", "Mobile", or "ICS"
6. Click "Create layer from version"

### Browsers Tested:
- Chrome
- Firefox
- Safari

(Caches were cleared before each test.)

**Comment by clemiller** [comment]
Thank you for reporting this bug! We've issued a patch release with a fix on Navigator v4.9.3. Please let us know if you run into any other issues!

**Comment by mikecarenzo** [comment]
Awesome! Thanks for the fast turnaround on this!
