### ISSUE TITLE
Selecting data sources doesn't work anymore

### ISSUE THREAD

**Issue by ianlav01** [mitre-attack/attack-navigator#622]
when you try to select a data source to highlight relevant techniques/sub techniques, you get the following error:
ERROR TypeError: e.get_all_technique_tactic_ids is not a function or its return value is not iterable

![image](https://github.com/mitre-attack/attack-navigator/assets/115007081/76602793-d7cc-4cbb-bec1-8e473be34f36)

**Comment by clemiller** [comment]
Hi @ianlav01, thanks for opening up a bug report for this! We've issued a patch release with a fix on Navigator v4.9.4.
