### ISSUE TITLE
Exporting to JSON seems broken.

### ISSUE THREAD

**Issue by OtherPeoplesEnemy** [mitre-attack/attack-navigator#630]
When I create a layer and export to json I only get this its missing all the categories and TTPs

{
	"name": "Red Team",
	"versions": {
		"attack": "14",
		"navigator": "4.9.4",
		"layer": "4.5"
	},
	"domain": "enterprise-attack",
	"description": "",
	"filters": {
		"platforms": [
			"Linux",
			"macOS",
			"Windows",
			"Network",
			"PRE",
			"Containers",
			"Office 365",
			"SaaS",
			"Google Workspace",
			"IaaS",
			"Azure AD"
		]
	},
	"sorting": 0,
	"layout": {
		"layout": "side",
		"aggregateFunction": "average",
		"showID": true,
		"showName": true,
		"showAggregateScores": false,
		"countUnscored": false,
		"expandedSubtechniques": "none"
	},
	"hideDisabled": false,
	"techniques": [],
	"gradient": {
		"colors": [
			"#ff6666ff",
			"#ffe766ff",
			"#8ec843ff"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"links": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": true,
	"selectSubtechniquesWithParent": false,
	"selectVisibleTechniques": false
}

**Comment by OtherPeoplesEnemy** [comment]
Looks like if you toggle the state it works.

**Comment by Dviros** [comment]
Can confirm this actually happens to me too.
Steps to reproduce:
1. Access Navigator (https://mitre-attack.github.io/attack-navigator/), select Enterprise only with the latest version.
2. Filter out on 365, SaaS, Google Workspace, Azure AD
3. Select T1530 - it appears, state is on.
4. Expand on all techniques and sub-techniques
5. Export as JSON and Excel, search for T1530
6. Technique would appear in the excel file and not in the JSON file

[layer.xlsx](https://github.com/mitre-attack/attack-navigator/files/15324945/layer.xlsx)
[layer (3).json](https://github.com/mitre-attack/attack-navigator/files/15324947/layer.3.json)
