### ISSUE TITLE
ATLAS JSON without repeats from enterprise

### ISSUE THREAD

**Issue by MagnificentCreature** [mitre-attack/attack-navigator#644]
Is there a file like
'https://raw.githubusercontent.com/mitre-atlas/atlas-navigator-data/main/dist/stix-atlas.json'
that doesn't have the repeat tactics and techniques from enterprise?

ie only AI threats

Thank you

**Comment by clemiller** [comment]
Hi @MagnificentCreature,

ATLAS is developed and maintained by a separate team, I'd recommend reaching out directly to them ([atlas@mitre.org](mailto:atlas@mitre.org), https://atlas.mitre.org/resources/contact/), or opening an issue in their GitHub repository for more information:
- [atlas-data](https://github.com/mitre-atlas/atlas-data)
- [atlas-navigator](https://github.com/mitre-atlas/atlas-navigator)
