### ISSUE TITLE
Install File (npm) Not found in \nav-app directory

### ISSUE THREAD

**Issue by GeorgePaul2383** [mitre-attack/attack-navigator#66]
Thank you for the wonderful work you guys are doing @mitre.

I can not find the Install File (npm in the \nav-app directory,

herewith the instructions

**Install and Run
First time
Navigate to the nav-app directory
Run npm install**

Please, can someone assist?

**Comment by isaisabel** [comment]
Hi @GeorgePaul2383,

Sorry for taking so long to get back to you. 

`npm` is not an install file, but a dependency — the node project manager, which is bundled with [NodeJS](https://nodejs.org/en/) (noted under [requirements](https://github.com/mitre-attack/attack-navigator#requirements)).

If you install NodeJS you should be able to run the `npm install` command to install dependencies.
