### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#71]
An accessibility nice-to-have would be multiple visual themes for the Navigator. People working in low-light environments may find the white background of our current theme blinding. Adding an alternate color scheme with a dark background and light text (a "dark theme") would improve usability for demos or workspaces with lower light levels. 

Optimally the user would be able to change the theme live in the application (perhaps using a dropdown next to the help button in the top right). The application should remember the previous theme selection using cookies.

**Comment by jinxka** [comment]
A better solution is to use the direct css selector [prefers-color-scheme](https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-color-scheme) instead of cookies.

Thank you.

**Comment by isaisabel** [comment]
@jinxka thanks for pointing that out, I didn't know that existed! I think there are cases where a user may want to override that setting, but it'd definitely be good to allow the user's OS selected theme to be inherited. Like how Slack allows for the user to sync theme with OS settings or override for that specific application:

![image](https://user-images.githubusercontent.com/28868888/132342037-4888be13-0119-4ecc-a1e7-21ba60de1c56.png)

**Comment by agg-mb** [comment]
@isaisabel Thanks for the implementation. I might have overseen it, but I am afraid I couldn't find the option to turn on the dark theme. In the help menu at the top right there's no documentation of the dark theme, could it please be added there?

In short: How do I turn on the dark theme?

Thanks!

**Comment by isaisabel** [comment]
Hi @agg-mb,

The dark theme control is available on the new tab interface here:

<img width="1248" alt="Screenshot 2023-05-25 at 1 13 45 PM" src="https://github.com/mitre-attack/attack-navigator/assets/28868888/69d0ae70-3add-4f05-ae95-7e20c401b080">

You seem to be correct that the USAGE document does not mention the dark theme. I'm not actually maintaining ATT&CK Navigator anymore so I'll leave that potential change to the current maintainers (@clemiller from the look of it).

**Comment by agg-mb** [comment]
Thanks so much @isaisabel !

One more question @clemiller :
Is it possible yet to render the SVG in the dark theme? it comes out as light themed for me:
![image](https://github.com/mitre-attack/attack-navigator/assets/134610601/fb87836b-5c62-451b-a548-23fd842691d5)

**Comment by jondricek** [comment]
@agg-mb I created a new issue to track the request for SVG output having a dark theme. Short answer is that it is not possible right now however. Thank you for the request though!

https://github.com/mitre-attack/attack-navigator/issues/556
