### ISSUE TITLE
Generate SVG File via API

### ISSUE THREAD

**Issue by aggie0642** [mitre-attack/attack-navigator#74]
We would like the ability to POST a JSON layer file (or specify a URL hosting one) to an HTTP API endpoint and have the returned data be the rendered SVG file.

This will allow us to update our image files via a script.

**Comment by isaisabel** [comment]
Hi @aggie0642,

The ATT&CK Navigator doesn't utilize any serverside processing so creating an API for layer generation is outside of our scope.

I would recommend taking a look at our [exporter component](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/exporter/exporter.component.ts) as a possible starting point for an SVG rendering script. We use d3js for creating the exported table - it looks like [svgcreator](https://github.com/hugolpz/svgcreator.node.js) might be a viable way to render the svg without a browser window.
