### ISSUE TITLE
Extend layerURL query param to allow multiple layers on initialization

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-navigator#75]
Now that the config file allows the user to load multiple default-layers (#67), the alternative default-layer methodology -- the layerURL query param specified by #20 -- is comparatively less functional because it can only load a single default layer. 

The feature should be extended to match the extended functionality of default_layers in the config file.

**Comment by timtheguy** [comment]
Hi @isaisabel - are you open to open source contributions on this project? If so, I'd love to try and tackle this issue. Thanks in advance!

**Comment by isaisabel** [comment]
Hi @timtheguy,

Yes! Check out our [contributing document](https://github.com/mitre-attack/attack-navigator/blob/master/CONTRIBUTING.md) for more details. 

Some notes for this specific feature:
-  We're trying to get this feature finished by October 21 as part of our [Version 2.2.2 milestone](https://github.com/mitre-attack/attack-navigator/milestone/2). 
- It is also important that the extended functionality of the layerURL query string is backwards compatible with the current implementation of the feature. 
- The "Create Customized Navigator" UI should be extended to allow the user to specify multiple layer URLs. If you just want to handle the back-end stuff, feel free to just work on that and I can add the UI portion myself.

Let me know if you have any questions. Thanks,

Isabel

**Comment by isaisabel** [comment]
Hi @timtheguy,

Have you started working on this feature yet? We're trying to get it released as part of our [Version 2.3 milestone](https://github.com/mitre-attack/attack-navigator/milestone/2), which is due on the 21st. 

Thanks,

Isabel

**Comment by isaisabel** [comment]
Implemented in [feature/multiple_layerURLs](https://github.com/mitre-attack/attack-navigator/tree/feature/multiple_layerURLs) and merged into develop.
