### ISSUE TITLE
Feature Request: Automatically Generate Technique HeatMap

### ISSUE THREAD

**Issue by ssnkhan** [mitre-attack/attack-navigator#83]
When selecting multiple Threats Groups/Software via the Selection tool, allow the system to automatically generate a heatmap based on the frequency a technique is used.

Most used = most intense colour
Least used = lowest intensity/transparency

The current gradient system relies on each technique being manually scored. However, for a general overview of technique usage, the technique count is lost once multiple Threat Groups/Software are added to the matrix.

A similar view is implemented within Unfetter here: https://nsacyber.github.io/unfetter/intrusion.html

**Comment by isaisabel** [comment]
Hi @ssnkhan,

We think this is a really neat idea, however it doesn't quite fall under the scope of the ATT&CK Navigator. The Navigator is not intended to automatically generate annotations based on ATT&CK content, but rather as a tool to manually create and/or visualize annotations. Such annotation generation would be better suited to a standalone script in our [attack-scripts](https://github.com/mitre-attack/attack-scripts) repository. The script would generate a layer file with those frequencies as scores, which could then be visualized with the ATT&CK Navigator or [the layer renderer script proposed here](https://github.com/mitre-attack/attack-scripts/issues/1).

Feel free to [resubmit this issue in that repository](https://github.com/mitre-attack/attack-scripts/issues/new).
