### ISSUE TITLE
Attempting to setup on-prem ATT&CK Navigator shows multiple high vulnerabilities?

### ISSUE THREAD

**Issue by willemdh** [mitre-attack/attack-navigator#86]
A colleague tried to install ATT&CK Navigator on-premise like this:

```
H:\attack-navigator\nav-app>dir
Volume in drive H is home
Volume Serial Number is 80F4-1229

Directory of H:\attack-navigator\nav-app

09/05/2019  13:20    <DIR>          .
09/05/2019  13:15    <DIR>          ..
09/05/2019  13:15               258 .editorconfig
09/05/2019  13:15               558 .gitignore
09/05/2019  13:15             4.294 angular.json
09/05/2019  13:15               223 Dockerfile
09/05/2019  13:15    <DIR>          e2e
09/05/2019  13:15             1.088 karma.conf.js
09/05/2019  13:20    <DIR>          node_modules
09/05/2019  13:15           530.191 package-lock.json
09/05/2019  13:15             1.875 package.json
09/05/2019  13:15               453 patch-webpack.js
09/05/2019  13:15               750 protractor.conf.js
09/05/2019  13:15    <DIR>          src
09/05/2019  13:15               428 tsconfig.json
09/05/2019  13:15             3.111 tslint.json
              11 File(s)        543.229 bytes
               5 Dir(s)     618.233.856 bytes free

H:\attack-navigator\nav-app>npm install

> node-sass@4.9.3 install H:\attack-navigator\nav-app\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\me\AppData\Roaming\npm-cache\node-sass\4.9.3\win32-x64-64_binding.node

> node-sass@4.9.3 postinstall H:\attack-navigator\nav-app\node_modules\node-sass
> node scripts/build.js

Binary found at H:\attack-navigator\nav-app\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'H:\attack-navigator\nav-app\node_modules\fsevents\node_modules'

> nav-app@1.0.0 postinstall H:\attack-navigator\nav-app
> node patch-webpack.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular-devkit\core\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1447 packages from 1316 contributors and audited 25278 packages in 572.414s
**found 30 vulnerabilities (2 low, 4 moderate, 24 high)**
  run `npm audit fix` to fix them, or `npm audit` for details
```

Our concern is the following:

**found 30 vulnerabilities (2 low, 4 moderate, 24 high)**

Bit weird for an application that is meant to make things 'more' secure? Or are we missing something?

**Comment by isaisabel** [comment]
Hi @willemdh,

Thank you for notifying us of these vulnerabilities. We try to keep our node modules up to date but we don’t release updates to this project very frequently. The ATT&CK Navigator is reasonably compartmentalized (its only external request is for data to populate the matrix, and this can be disabled if you have local data instead) so these vulnerabilities are not as problematic as they could be — though we do of course still intend to patch them in our next update.

In the meantime you can run the following commands to patch your local version:

1. `npm audit fix` fixes the majority of the vulnerabilities
2. `npm audit fix --force` forces the remainder to update
3. `node patch-webpack.js` patches an issue with webpack. Normally this runs automatically after `npm install` however it needs to be run manually in this case.

After taking these steps there will still be one vulnerability with `tar` which won’t be patched. [This is an issue with angular-cli’s dependency tree and is not easily fixed until they update their dependencies themselves](https://github.com/angular/angular-cli/issues/14138).

**Comment by isaisabel** [comment]
Hi @willemdh, 

This morning we released a new version of the Navigator which patches all of the vulnerabilities, including the one with `tar` which as of my last comment didn't have a fix.
