### ISSUE TITLE
warning in ./node_modules/exceljs/node_modules/sax/lib/sax.js

### ISSUE THREAD

**Issue by jeandez** [mitre-attack/attack-navigator#90]
Hello , 

I am tryng to install  ATT&ck but i am facing error with **ExcelJs.**

**Detail below :**

WARNING in ./node_modules/exceljs/node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in '/home/jeandez/Desktop/Attack/attack-navigator-master/nav-app/node_modules/exceljs/node_modules/sax/lib'

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir '/home/jeandez/Desktop/Attack/attack-navigator-master/nav-app/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:790:3)
    at Object.getInstalledBinaries (/home/jeandez/Desktop/Attack/attack-navigator-master/nav-app/node_modules/node-sass/lib/extensions.js:129:13)

**i tried to fix it by un modifying tsconfing.json in vain.
Could you help me  ??
thank you.**

**Comment by isaisabel** [comment]
Hi @jeandez,

We released a new minor version of the Navigator today which updated many of our dependencies. It is possible that this update addressed the issue you're seeing here. Could you try installing the latest version? 

Thanks!

**Comment by jeandez** [comment]
Hello , thank you for your anwser. He works fine.

Cdlt,

 

    Le mercredi 5 juin 2019 à 15:56:44 UTC+2, Isabel Trahan <notifications@github.com> a écrit :  
 
 
Hi @jeandez,

We released a new minor version of the Navigator today which updated many of our dependencies. It is possible that this update addressed the issue you're seeing here. Could you try installing the latest version?

Thanks!
