### ISSUE TITLE
Installation Module Issues

### ISSUE THREAD

**Issue by nitinpunn** [mitre-attack/attack-navigator#93]
I have gotten the navigator running on my mac but when installing on an AWS Ubuntu instance, or even an Amazon Linux instance, I receive the following errors. Seems very similar to a previous issue. npm install os and npm install stream seem to solve those errors but npm install fs does not fix any of those errors

Your global Angular CLI version (8.0.3) is greater than your local
version (8.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Date: 2019-06-24T15:47:58.935Z
Hash: 3a869f6a6c7f0ecb2390
Time: 16502ms
chunk {main} main.js, main.js.map (main) 629 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 562 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 462 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 2.18 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 197 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.59 MB [initial] [rendered]

WARNING in ./node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/sax/lib'

ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/csv'
ERROR in ./node_modules/exceljs/dist/es5/utils/utils.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/utils'
ERROR in ./node_modules/exceljs/dist/es5/xlsx/xlsx.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/xlsx'
ERROR in ./node_modules/fast-csv/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/extended.js
Module not found: Error: Can't resolve 'os' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib'
ERROR in ./node_modules/exceljs/dist/es5/utils/stream-buf.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/utils'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/attack-navigator/nav-app/node_modules/jszip/lib'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.

**Comment by isaisabel** [comment]
Hi @nitinpunn,

It looks like the postinstall step is not running. `npm` _should_ automatically run the postinstall step after `npm install`, however it's possible that this is not happening due to your environment (I'm not personally familiar with the AWS Ubuntu or Amazon Linux environments however I've seen instances where postinstall hasn't run under certain environments before).

Try running `npm run postinstall` from the `nav-app` directory. This will run the [patch-webpack.js](/nav-app/patch-webpack.js) script which was implemented in order to fix these errors.

Let me know if that helps.

**Comment by nitinpunn** [comment]
That fixed the problem, thank you so much!
