### ISSUE TITLE
Utilizing custom matrix

### ISSUE THREAD

**Issue by nitinpunn** [mitre-attack/attack-navigator#94]
I was wondering if it's possible to use your own techniques and tactics matrix such as the one in the picture.
![Screen Shot 2019-07-02 at 10 40 15 AM](https://user-images.githubusercontent.com/36107629/60521928-1ada3600-9cb6-11e9-8f2c-a7a38b7eab3e.png)

**Comment by isaisabel** [comment]
Hi @nitinpunn,

Yes, It is possible to utilize a custom matrix though somewhat complicated. 

First, create custom STIX bundles for your content. Check out the MITRE/CTI repo [here](https://github.com/mitre/cti), and the [usage documentation](https://github.com/mitre/cti/blob/master/USAGE.md), for more info on how you might go about formatting the data. The data you'd need to create would be of the following types: 
- `attack-pattern` (technique): Defines all of the techniques in your dataset. The name and tactics (`kill_chain_phases`) of each technique are defined in these objects.
-`x-mitre-tactic` (tactic): Defines all the tactics in your dataset — most importantly the tactic names come from these objects.
-`x-mitre-matrix` (matrix): Defines the order of tactics in your matrix.

Second, create a local instance which is configured to pull data from local files (see instructions [here](https://github.com/mitre-attack/attack-navigator#Loading-content-from-local-files)). Set it up to pull from your custom STIX bundles.

**Comment by nitinpunn** [comment]
Hi! So i've created a custom stix bundle but how do I use the custom bundle? The navigator comes up blank when I follow the directions to use local files

**Comment by nitinpunn** [comment]
@isaisabel forgot to mention you

**Comment by nitinpunn** [comment]
actually never mind, i got it working

**Comment by will-giraldo-d** [comment]
@nitinpunn How did you fix the issue being blank? I am having the same problem.
