### ISSUE TITLE
Example of Log sources based on Data Sources

### ISSUE THREAD

**Issue by palevelmode** [mitre-attack/attack-navigator#95]
Hi All,

I would like to ask you can refer me to the sample log sources for each data sources.

Let say Authentication logs, what are the logs which can I the can get log sources from this. is FW, network, IPS devices are included as a sources for this type of data source? After all we can get authentication messages from these network devices?

Another example are API logs, Sensor health and status. Can this be a health status of FW or a server?

**Comment by isaisabel** [comment]
Hi @palevelmode,

This question is out of scope for the ATT&CK Navigator. This issue tracker is typically used for technical support, feature requests, bug reports and usage questions about the application, not questions about ATT&CK itself. Questions like this regarding the content of ATT&CK are better directed to attack@mitre.org.

Best,

Isabel
