### ISSUE TITLE
Docker : Build command failing

### ISSUE THREAD

**Issue by srkolli** [mitre-attack/attack-navigator#97]
I am trying to build docker image on CentOS Linux release 7.6.1810 

docker build -t  mitrepoc .

Sending build context to Docker daemon 3.893 MB
Step 1/6 : FROM node:latest
Trying to pull repository docker.io/library/node ...
latest: Pulling from docker.io/library/node
a4d8138d0f6b: Pull complete
dbdc36973392: Pull complete
f59d6d019dd5: Pull complete
aaef3e026258: Pull complete
6e454d3b6c28: Pull complete
c717a7c205aa: Pull complete
543d5a743e8e: Pull complete
5a2bc083aabd: Pull complete
ba44fd9296ef: Pull complete
Digest: sha256:b08b5d1049f9dd465962ec9b1b26cf1b13021914553836c155a83ebfa899e440
Status: Downloaded newer image for docker.io/node:latest
 ---> 9bc0f9cbb805
Step 2/6 : WORKDIR /nav-app/
 ---> b1057e4a02b7
Removing intermediate container 5ac74911af3b
Step 3/6 : COPY . ./
 ---> b2c56d409658
Removing intermediate container 3825bb989148
Step 4/6 : RUN npm install --unsafe-perm
 ---> Running in d88d65ed45f8

Error: EACCES: permission denied, scandir '/nav-app'
(node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:112:20
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'loaded' of undefined
    at process.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:39:18)
    at process.emit (events.js:203:13)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:215:3)
    at process.emit (events.js:203:13)
    at process._fatalException (internal/process/execution.js:150:25)
The command '/bin/sh -c npm install --unsafe-perm' returned a non-zero code: 7
[root@centos73_v182101_01 nav-app]# ls -lrt

**Comment by isaisabel** [comment]
Hi @srkolli,

The error line which reads `Error: EACCES: permission denied, scandir '/nav-app'` implies to me that this is an issue with directory permissions when running the `npm install` step. [This post](https://testcafe-discuss.devexpress.com/t/docker-file-install-npm-package-permission-denied/992/2) may provide a solution.

Let me know if that works.

**Comment by srkolli** [comment]
Thank you. I used this link to resolve the issue [
![image](https://user-images.githubusercontent.com/1201017/63106570-1a89b780-bf51-11e9-8c10-57466d124650.png)
](url)
